### ISSUE TITLE
Using KBFS with `keybase oneshot`?

### ISSUE THREAD

**Issue by woodruffw** [keybase/client#11805] opened 2018-05-11 21:43 UTC
Hi there,

I'm trying to move my CI setup from `keybase login` + `expect` to `keybase oneshot`, but I'm having problems getting KBFS to function correctly.

Here's what I've been doing (on the CI, as setup):

```bash
# `keybase service` doesn't start KBFS, so run `run_keybase` instead
$ run_keybase

# $KEYBASE_USERNAME and $KEYBASE_PAPERKEY are set correctly
$ keybase oneshot

$ mkdir /var/run/user/1000/keybase/kbfs/private/${KEYBASE_USERNAME}/foo
mkdir: Permission denied
```

I'm not sure if it's related, but I also see some inconsistent information in `keybase status -j` when trying to replicate the behavior in a VM -- sometimes `Username` and `LoggedIn` are populated correctly (with `$KEYBASE_USERNAME` and `true`, respectively), and sometimes they're `""` and `false`, respectively, even after running `keybase oneshot`.

Most of my WIP is here: https://github.com/kbsecret/kbsecret/pull/74

Any thoughts?

**Comment by maxtaco** [comment] 2018-05-12 12:42
Can you send a ‘keybase log send’?

**Comment by woodruffw** [comment] 2018-05-12 14:42
Here you go: `6db8f5f0e8a7edd2a5291f1c`.

`keybase log send` also spat out `INFO Not sending a UID for logged in user; none found`, in case that's relevant.

**Comment by maxtaco** [comment] 2018-05-12 14:53
Thanks @woodruffw, there's definitely a bug in your log, I'll take a look on Monday. It's likely a recent regression. BTW, your account is definitely an outlier since you've revoked and added so many devices.  Hopefully oneshot fixes this going forward.

**Comment by woodruffw** [comment] 2018-05-12 15:14
Thanks! And sorry about the devices :slightly_smiling_face:

**Comment by maxtaco** [comment] 2018-05-12 16:29
Repro'ed, I put a PR up here: https://github.com/keybase/client/pull/11813/files

**Comment by woodruffw** [comment] 2018-05-12 17:46
Awesome! I'll test in a bit.

**Comment by maxtaco** [comment] 2018-05-12 18:44
No problem. Merged into master. Thanks for the bug report.

**Closed by maxtaco** 2018-05-12 18:44 UTC
Labels: acked
