### ISSUE TITLE
needs fulltext search

### ISSUE THREAD

**Issue by crowlogic** [keybase/client#14239] opened 2018-10-13 23:51 UTC
Integration with something like http://www.lesbonscomptes.com/recoll/ would be nice, or building the feature into the client

**Comment by dlumma** [comment] 2019-07-16 13:58
I think this may be a duplicate of this: https://github.com/keybase/client/issues/18417

**Comment by dlumma** [comment] 2019-07-16 13:58
@strib FYI

**Closed** 2022-08-08 19:46 UTC
