### ISSUE TITLE
can't upload file

### ISSUE THREAD

**Issue by ntcastro** [keybase/client#12987] opened 2018-07-26 01:26 UTC
Hi,

Trying to upload a file to a shared private folder. It lets me select from my computer, then even flashes "Encrypting and Uploading" at the bottom in the blue bar. Never appears. I've tried multiple files, even in other places in the folder structure, no luck. I rebooted the computer, then uninstalled/reinstalled keybase as well. Help?

NTC

**Comment by a2** [comment] 2018-07-26 09:52
I'm seeing a similar issue. In the Keybase app for macOS, I get this:

> Error: ERROR CODE 218 - Error checking merkle tree: can't operate on old merkle sequence number in method keybase.1.SimpleFS.simpleFSWait

And if I try via the CLI, I get this: 

> $ keybase fs cp index.html /keybase/public/a2
▶ ERROR Error checking merkle tree: can't operate on old merkle sequence number

**Comment by strib** [comment] 2018-07-26 14:03
@a2 we're looking at your case already today.

@ntcastro please do a `keybase log send` and post the log ID here.

**Comment by ntcastro** [comment] 2018-07-26 19:44
Apologies, I don't know how to do that. It says to open a terminal window
for that, but can you just hold my hand on how to do that? Thanks!

**Comment by strib** [comment] 2018-07-26 19:50
@ntcastro what operating system is your computer running?

**Comment by ntcastro** [comment] 2018-07-26 19:53
Windows 10 Home. I thought I was looking for a terminal window within
keybase, that was silly.

Log ID is: 0c4314c703b649a304109c1c

Thanks!
Nicole

**Comment by strib** [comment] 2018-07-26 20:13
I followed up with @ntcastro privately, and the issue is that uploading files through the GUI in Windows doesn't work right now.  We're working on fixing that bug, but for now, accessing the files through Windows explorer worked around the problem.

**Comment by a2** [comment] 2018-07-27 07:08
@strib Thanks so much. Let me know if I can provide more information about my set-up/situation here. Happy to help in any way I can.

**Comment by strib** [comment] 2018-08-08 14:07
@a2 yes sorry, still on the todo list.  Will get to it soon.  (Though you're running a slightly old version, it's still not fixed in the newest version.)

**Comment by a2** [comment] 2018-08-08 14:08
@strib Thanks for the update in either case :)

**Comment by strib** [comment] 2018-08-08 17:35
@a2 thanks for the reminder about this.  Our next release isn't scheduled for a while, but I made a special build for you including a possible fix, if you're interested in trying it.  You can download it here: https://s3.amazonaws.com/prerelease.keybase.io/darwin-test/Keybase-2.6.0-20180808172014%2B2caa6bc657.dmg

(It's the same as our current release, but with the KBFS commits linked above.)

Let me know if it improves things for you!

**Comment by a2** [comment] 2018-08-10 07:03
@strib It works now!! Thank you so much for your help.

**Comment by strib** [comment] 2018-08-10 14:25
Great!

**Closed by strib** 2018-08-10 14:25 UTC
Labels: acked
