### ISSUE TITLE
`keybase version` gives error if server isn’t started

### ISSUE THREAD

**Issue by lucaswerkmeister** [keybase/client#1923] opened 2016-02-06 13:03 UTC
```
$ keybase ctl stop
$ keybase version
▶ ERROR dial unix /run/user/1000/keybase/keybased.sock: connect: no such file or directory
```
Most other commands seem to start the server if it isn’t running already. Alternatively, it might make sense for this command to just print the client version if the server isn’t running. But this error shouldn’t happen, I think.

I’m on version 1.0.10-0 (Arch package).

**Comment by maxtaco** [comment] 2016-02-06 13:47
Thanks! This was by design but another bug crept in that prevents it from
displaying the service isn't running before crapping out.

**Comment by maxtaco** [comment] 2016-02-08 16:34
Should be fixed in our latest update (1.0.10). Thanks for the bug report.

**Closed by maxtaco** 2016-02-08 16:34 UTC

**Comment by lucaswerkmeister** [comment] 2016-02-12 20:23
Can confirm it’s fixed in 1.0.11. Thanks!
