### ISSUE TITLE
No CLI tools installed

### ISSUE THREAD

**Issue by ardian** [keybase/client#4468] opened 2016-09-30 06:46 UTC
Hi,

Just installed Keybase, was able to sign in but the command line tool isn't installed. Tried downloading it twice, same issue. I'm on OS X Sierra

Keybase GUI Version: 1.0.17-20160922174631+f87e42c

**Comment by sjafferali** [comment] 2016-10-03 17:57
I had the same issue, but it turns out the binary was just not located in my $PATH variable. I was able to resolve it by manually symlinking the binary to a location within my $PATH. Full details on my temporary fix can be found in the bug I submitted #4491 .

**Comment by gabriel** [comment] 2016-10-03 20:02
Dupe of https://github.com/keybase/client/issues/4398

**Closed by gabriel** 2016-10-03 20:02 UTC
