### ISSUE TITLE
upd.exe being flagged as a trojan by 12 antivirus solutions

### ISSUE THREAD

**Issue by Zenexer** [keybase/client#7926] opened 2017-07-28 01:55 UTC
upd.exe is being flagged as Graftor by 12 antivirus solutions: https://www.virustotal.com/en/file/70b6675fac69b755dc716b1b6ee14617df15d340eb0aea7f91f3de120fcc603f/analysis/

It sounds like this is likely a false positive.

**Comment by Zenexer** [comment] 2017-07-28 02:01
I rescanned the file; looks like it's down to 6 false positives now.  12 were detected yesterday.

**Comment by kkarhan** [comment] 2017-08-02 13:04
the issue has been repeatedly posted.
all errors are generics.
now down to 4 false positives.

**Comment by zanderz** [comment] 2017-08-02 17:58
Duplicate of https://github.com/keybase/client/issues/7908

**Closed** 2017-11-09 09:46 UTC
