### ISSUE TITLE
Keybase Binary not in $PATH on Mac OS Sierra

### ISSUE THREAD

**Issue by sjafferali** [keybase/client#4491] opened 2016-10-03 17:55 UTC
I just installed the keybase app on a new Mac running Sierra. For some reason, the keybase binary was not in my $PATH variable. 

Not sure if it is suppose to automatically get symlinked somewhere in my $PATH variable (as I do not have the previous Mac that I installed this on), but I was able to resolve it by manually symlinking the binary. 

```
samir@macbook [~]$ ln -s /Applications/Keybase.app/Contents/SharedSupport/bin/keybase /usr/local/bin/keybase
samir@macbook [~]$
```

my log id: e64a9b2d8a9a43d16ceacc1c

**Comment by gabriel** [comment] 2016-10-03 20:02
Dupe of https://github.com/keybase/client/issues/4398

**Closed by gabriel** 2016-10-03 20:02 UTC
