### ISSUE TITLE
Keybase GUI shows blank-ish dialogs

### ISSUE THREAD

**Issue by chungy** [keybase/client#2024] opened 2016-02-15 06:55 UTC
On Arch Linux using GNOME 3, the GUI just displays opaque blobs of color. I suspect one of them is key unlocking, but I can't really tell.

I don't seem to be able to use kbfs either, possibly as a result of this.

Initial dialog:
![Initial dialog](https://i.imgur.com/GSLHXRi.png)

When I click the icon:
![Grey blob](https://i.imgur.com/GtBonv0.png)

my log id: c13df03ad6cf0703c6c69f1c

**Comment by chungy** [comment] 2016-02-15 07:07
I managed to use it manually by invoking kbfsfuse myself and using `keybase unlock` :-)

**Comment by oconnor663** [comment] 2016-02-15 19:52
Crazy. I'm on Arch Gnome 3 myself, but I don't have this problem. Do you know what GPU and driver package you have? (I'm using a integrated Intel GPU, with the `xf86-video-intel` drivers.)

**Comment by chungy** [comment] 2016-02-15 21:49
I'm using a GTX 660 with the proprietary `nvidia` driver.

**Comment by blarghmatey** [comment] 2016-02-16 16:34
I'm having the same issue running Manjaro with KDE Plasma 5 on a hybrid Intel/Nvidia GPU setup with Optimus and leveraging bumblebee. If I try to use the `optirun` prefix then I don't get any window at all. I'm happy to provide any additional details that might be helpful.

**Comment by cjb** [comment] 2016-02-16 16:35
FWIW, KDE Plasma 5 works here on Ubuntu 15.10 with nVidia, as does GNOME 3.

**Comment by bdero** [comment] 2016-02-16 17:01
Hit the same problem as the others running Arch derivatives; I'm using Gnome 3 with the proprietary Nvidia driver: `NVIDIA Corporation GK107M [GeForce GT 650M Mac Edition] (rev a1)`

**Comment by cjb** [comment] 2016-02-16 17:22
So it looks like Arch+nVidia is the required combination for breakage.  Weird!

**Comment by cjb** [comment] 2016-02-16 18:45
Maybe we should all report nVidia driver *version* too?  Like, perhaps Arch packaged a different version to Ubuntu and that version that's in Arch is broken.

I'm on 355.11 on Ubuntu.

**Comment by blarghmatey** [comment] 2016-02-16 19:14
My driver information is as follows:
```
modinfo nvidia
filename:       /lib/modules/4.4.1-2-MANJARO/extramodules/nvidia.ko.gz
alias:          char-major-195-*
version:        352.79
supported:      external
license:        NVIDIA
alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        drm
vermagic:       4.4.1-2-MANJARO SMP preempt mod_unload modversions 
parm:           NVreg_Mobile:int
parm:           NVreg_ResmanDebugLevel:int
parm:           NVreg_RmLogonRC:int
parm:           NVreg_ModifyDeviceFiles:int
parm:           NVreg_DeviceFileUID:int
parm:           NVreg_DeviceFileGID:int
parm:           NVreg_DeviceFileMode:int
parm:           NVreg_UpdateMemoryTypes:int
parm:           NVreg_InitializeSystemMemoryAllocations:int
parm:           NVreg_UsePageAttributeTable:int
parm:           NVreg_MapRegistersEarly:int
parm:           NVreg_RegisterForACPIEvents:int
parm:           NVreg_CheckPCIConfigSpace:int
parm:           NVreg_EnablePCIeGen3:int
parm:           NVreg_EnableMSI:int
parm:           NVreg_MemoryPoolSize:int
parm:           NVreg_RegistryDwords:charp
parm:           NVreg_RmMsg:charp
parm:           NVreg_AssignGpus:charp
```

**Comment by cjb** [comment] 2016-02-16 19:21
@chungy Hi, which nVidia driver version are you using?

**Comment by chungy** [comment] 2016-02-16 19:24
I'm using 361.28-1 on x86_64 (should be the latest in the Arch repos).

**Comment by bdero** [comment] 2016-02-16 22:07
My modinfo:
```
modinfo nvidia
filename:       /lib/modules/4.4.1-2-ARCH/extramodules/nvidia.ko.gz
alias:          char-major-195-*
version:        361.28
supported:      external
license:        NVIDIA
srcversion:     28C04FA99D75F8B32C4AD02
alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        drm
vermagic:       4.4.1-2-ARCH SMP preempt mod_unload modversions 
parm:           NVreg_Mobile:int
parm:           NVreg_ResmanDebugLevel:int
parm:           NVreg_RmLogonRC:int
parm:           NVreg_ModifyDeviceFiles:int
parm:           NVreg_DeviceFileUID:int
parm:           NVreg_DeviceFileGID:int
parm:           NVreg_DeviceFileMode:int
parm:           NVreg_UpdateMemoryTypes:int
parm:           NVreg_InitializeSystemMemoryAllocations:int
parm:           NVreg_UsePageAttributeTable:int
parm:           NVreg_MapRegistersEarly:int
parm:           NVreg_RegisterForACPIEvents:int
parm:           NVreg_CheckPCIConfigSpace:int
parm:           NVreg_EnablePCIeGen3:int
parm:           NVreg_EnableMSI:int
parm:           NVreg_TCEBypassMode:int
parm:           NVreg_MemoryPoolSize:int
parm:           NVreg_RegistryDwords:charp
parm:           NVreg_RmMsg:charp
parm:           NVreg_AssignGpus:charp
```

**Comment by oconnor663** [comment] 2016-02-16 22:48
Could you all please tell me who has the `noto-fonts` package installed? It's a dependency of chromium and firefox, so it may be that everyone does. If anyone doesn't, would you please let me know if installing it fixes this problem?

**Comment by bdero** [comment] 2016-02-16 22:55
I did not have the `noto-fonts` package installed, although I do have firefox and chromium. Installing it didn't change the results in my case. One thing to note is that the UI elements aren't clickable, and the pinentry dialog renders as black after attempting to resize.

**Comment by oconnor663** [comment] 2016-02-16 22:57
Ah my mistake, `noto-fonts` "provides" `ttf-fonts`, which is what's actually required by those browsers, but lots of other packages also require that. I misread what pacman was telling me.

**Comment by chungy** [comment] 2016-02-16 22:59
Likewise didn't have `noto-fonts`, and installing it made no difference to keybase.

**Comment by neslinesli93** [comment] 2016-02-17 13:18
Same problem here, Manjaro Linux+XFCE, with nvidia gpu

**Comment by cjb** [comment] 2016-02-17 14:39
Sorry for the extra work, but could someone with broken Keybase please test whether the `atom-editor` package (text editor, uses Electron) works on your system?  We're using the same codebase as them, maybe it'll help figure something out.

**Comment by bdero** [comment] 2016-02-17 16:19
I use atom from time to time; I'm not experiencing the same issue with it:
![](https://my.mixtape.moe/gvbgrv.png)

**Comment by cjb** [comment] 2016-02-17 16:27
Cool, thanks.  We're pretty short on ideas.  At the moment we believe it's purely the combination of Arch + proprietary nVidia driver.. if anyone has access to a non-nVidia machine running Arch to test on, that'd be a useful sanity check.  Or even an Arch machine running nouveau instead of nvidia.

**Comment by cjb** [comment] 2016-02-17 16:31
https://github.com/atom/electron/issues/4380 !

**Comment by cjb** [comment] 2016-02-17 16:34
Please could someone try running:

/opt/keybase/Keybase --ignore-gpu-blacklist

**Comment by cjb** [comment] 2016-02-17 16:38
(The --ignore-gpu-blacklist tip comes from https://github.com/ethereum/meteor-dapp-wallet/issues/78.)

**Comment by bdero** [comment] 2016-02-17 16:42
Those issues definitely look relevant! I tried running with the `--ignore-gpu-blacklist` flag, but it looks as though the results didn't change.

**Comment by bdero** [comment] 2016-02-17 16:44
But, maybe it's because it needs to be passed to one of the subprocesses:
```
bdero     9352  0.0  0.0  41380  8048 pts/5    Ss   11:14   0:00  \_ /bin/zsh
bdero    10417  3.1  0.7 1357176 117440 pts/5  Sl+  11:42   0:01  |   \_ /opt/keybase/Keybase --ignore-gpu-blacklist
bdero    10419  0.0  0.1 318348 31192 pts/5    S+   11:42   0:00  |       \_ /opt/keybase/Keybase --type=zygote --no-sandbox
bdero    10454  2.5  0.6 1041936 100088 pts/5  Sl+  11:42   0:00  |       |   \_ /opt/keybase/Keybase --type=renderer --no-sandbox --lang=en-US --node-integration=true --num-raster-threads=4 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553 --channel=10417.2.1505476042 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
bdero    10439  1.4  0.6 466344 100644 pts/5   Sl+  11:42   0:00  |       \_ /opt/keybase/Keybase --type=gpu-process --channel=10417.0.585651717 --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=2,32,35,51,61,63 --gpu-vendor-id=0x10de --gpu-device-id=0x0fd5 --gpu-driver-vendor=NVIDIA --gpu-driver-version=361.28 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
```

**Comment by cjb** [comment] 2016-02-17 16:56
I guess you could try installing your own version of Electron (there's an AUR package) and then:

cd /opt/keybase
electron . --ignore-gpu-blacklist

That's what someone in the meteor-dapp-wallet ticket tried.  Thanks for all the debugging help!

**Comment by cjb** [comment] 2016-02-17 16:57
Or maybe that should be:

cd /opt/keybase
electron resources/app/ --ignore-gpu-blacklist

**Comment by chungy** [comment] 2016-02-17 17:36
I can run atom and running electron like that doesn't make a difference...

**Comment by cjb** [comment] 2016-02-17 17:45
This is super hacky, but if anyone wants to try:

* take a backup of /opt/keybase/resources/app/desktop/dist/main.bundle.js
* edit it, by replacing:

`appendSwitch("ignore-connections-limit","localhost")`

with

`appendSwitch("ignore-gpu-blacklist")

That might pass the flag down farther.  Revert your changes afterwards.  :)  You can run `/opt/keybase/Keybase` to test, don't need to use separate electron.

**Comment by chungy** [comment] 2016-02-17 22:23
Didn't make a difference.

**Comment by cjb** [comment] 2016-02-17 22:25
Rats.  Thanks very much for the test anyway.

**Comment by cjb** [comment] 2016-02-19 14:48
I guess the next test I'd like to ask for is seeing if it works when any of you use nouveau instead of nvidia as graphics driver, but I understand that that's very disruptive.  Thanks for the debugging attempts so far!

**Comment by oconnor663** [comment] 2016-02-20 00:50
Ok, I just installed a GeForce GTX 960 and the `nvidia` driver in my Arch machine. (`modinfo nvidia` identical to @bdero's above.) As a result I am currently experiencing...*drum roll*...no rendering issues :|

![image](https://cloud.githubusercontent.com/assets/860932/13192987/018832b8-d740-11e5-8e80-ecd6678141ff.png)

That said, I'm pretty sure I've misconfigured something. Desktop animations in Gnome 3 are extremely choppy, and `vblank_mode=0 glxgears` is giving me ~1900 fps, which is less than a third of what I see on my little laptop with its integrated Intel graphics chip.

**Comment by cjb** [comment] 2016-02-20 01:22
@oconnor663 Huh! `sudo nvidia-settings` might tell you some things about the status.

**Comment by cjb** [comment] 2016-02-20 22:24
@pritambaral hit this bug without using nvidia! So the graphics stuff might be a red herring.

**Comment by oconnor663** [comment] 2016-02-22 15:24
Ok, @cjb helped me fix my performance issues. Turns out I had mesa-libgl installed instead of nvidia-libgl. (Should I be surprised that desktop rendering worked at all?) Anyway having fixed that problem, I still can't repro the blank Keybase windows, so the mystery continues...

**Comment by oconnor663** [comment] 2016-02-22 15:44
GOT IT! I had `fontconfig-ubuntu`, `freetype2-ubuntu`, and `cairo-ubuntu` installed. When I replaced those with the standard packages, the bug finally repro'd. I'll try to narrow down which one it is.

**Comment by oconnor663** [comment] 2016-02-22 16:14
We narrowed it down to `freetype2`, and @cjb found https://github.com/atom/electron/issues/4513. Keybase uses Font Awesome, so ours is probably the same bug. Downgrading `freetype2` to version 2.6.2 is a workaround for now ([Arch Linux Archive link](http://seblu.net/a/archive/packages/f/freetype2/)).

**Comment by blarghmatey** [comment] 2016-02-22 16:24
@oconnor663 Nice work! Confirmed working on my machine.

**Comment by oconnor663** [comment] 2016-02-22 16:32
Filed an [Arch bug report](https://bugs.archlinux.org/task/48300) just in case. Looks like one's [already been filed](https://savannah.nongnu.org/bugs/index.php?47202) for freetype2.

**Comment by cjb** [comment] 2016-02-26 01:56
A fix (newer static harfbuzz) is in Electron master now, we'll pick it up next time they release.

**Comment by cjb** [comment] 2016-02-27 19:43
Electron has released v0.36.8 with a fix and we've upgraded to it, so I think you can stop downgrading freetype2 now.  Please reopen the bug if you see this again with latest keybase-git and freetype2.

**Comment by pritambaral** [comment] 2016-02-27 20:23
Still have the issue. Rebuilt from AUR `keybase-git`, had never downgraded freetype, ran `run_keybase` again, the window is just as bad as before.

Log id: 1e0780363ffbee47b3d2d91c

**Comment by cjb** [comment] 2016-02-27 20:27
Hm, I think @oconnor663 said something about maybe needing to manually update the AUR, perhaps that's it?

**Comment by oconnor663** [comment] 2016-02-27 20:41
Rebuilding should be enough. (The manual package version update I did was so that people who run something like `yaourt -Syua` to upgrade their whole system will automatically rebuild and reinstall `keybase-git`.)

@pritambaral, I see version `1.0.13-20160227200210+33bc1eb` in your logs. A fresh rebuild today should start with "1.0.14". Is it possible you rebuilt the package but didn't run `pacman -U` to install it, or something like that?

**Comment by pritambaral** [comment] 2016-02-27 20:43
@oconnor663 I did a `yaourt -S keybase-git`. It updated the git clone and rebuilt it. `-S` does `pacman -U` internally. I'll run another `yaourt -S` and check the version this time.

**Comment by pritambaral** [comment] 2016-02-27 20:55
@oconnor663 I think the PKGBUILD is incompatible with cached git repos. I have verified that I have `v1.0.14-1` pulled, and this is what I see:

<tt>==> Building and installing package</tt>
<tt>==> Making package: keybase-git <b>1.0.14</b>_20160226192715+54a2448-1 (Sun Feb 28 02:18:34 IST 2016)</tt>
<tt>==> Checking runtime dependencies...</tt>

But a few lines below:
<tt>==> Starting pkgver()...</tt>
<tt>==> Updated version: keybase-git <b>1.0.13</b>_20160227204838+33bc1eb-1</tt>
<tt>==> Starting build()...</tt>

Trying a build without caching, it's cloning right now.

----
By *cached git repos* I mean the `DEVELSRCDIR` option in `/etc/yaourtrc`

**Comment by pritambaral** [comment] 2016-02-27 21:23
@oconnor663 Cleanly rebuilding from AUR (which includes fresh git clones) also gives `1.0.13_20160227211513+33bc1eb-1`. Manually running the client/packaging/version.sh prerelease also gives `1.0.13_20160227211513+33bc1eb`

**Comment by oconnor663** [comment] 2016-02-27 21:47
I see the same last-checked-in version at the beginning

    ==> Making package: keybase-git 1.0.14_20160226192715+54a2448-1

(so we're definitely looking at the same `PKGBUILD`), but then the `pkgver()` output below gives me the current master version that I expect instead of the stale version you're seeing:

    ==> Updated version: keybase-git 1.0.14_20160227213207+cc71b63-1

Hmm. I'm not familiar with `DEVELSRCDIR`, but is it possible you somehow didn't do a totally clean build? I'm particularly suspicious of that hash `33bc1eb` in the version you're seeing -- that doesn't correspond to any of our branches or tags, and it doesn't appear in the `PKGBUILD` file, so I'm thinking it must be some kind of cached state on your machine. What "Updated version" do you see if you do something like this:

```
git clone https://aur.archlinux.org/keybase-git
cd keybase-git
makepkg --nobuild
```

**Comment by oconnor663** [comment] 2016-02-27 21:51
> Manually running the client/packaging/version.sh prerelease also gives 1.0.13_20160227211513+33bc1eb

What clone of the keybase repo is that script in? It must not be a fresh clone. Can you confirm (just to check my sanity) that you see the hash `33bc1eb` at the tip when you do a `git log` in that repo? My current best guess is that your builds are happening in this stale clone, maybe despite having made fresh clones somewhere else, though I don't know why that would be.

**Comment by oconnor663** [comment] 2016-02-27 21:59
Let's move this sub-issue to #2151, to avoid cluttering this issue too much.

**Comment by juliovalcarcel** [comment] 2016-03-02 14:36
So I have just ran a full update and rebuilt the keybase-git AUR package (Version 1.0.14-20160302142854+1db65e2) everything appears to be working without having to downgrade freetype2. My current version of freetype2 is 2.6.3-1

**Comment by cjb** [comment] 2016-03-02 15:03
Thanks, closing this issue.

**Closed by cjb** 2016-03-02 15:03 UTC
