### ISSUE TITLE
Mac Sidebar Showing Multiple Keybase drives

### ISSUE THREAD

**Issue by Deathmoon** [keybase/client#2154] opened 2016-02-29 14:27 UTC
<img width="190" alt="skitch" src="https://cloud.githubusercontent.com/assets/944610/13397097/5ccdb0a2-dec6-11e5-88ea-63b25ebe26b7.png">
This seems to only be a visual nuisance. Each time I log out or even restart, the Mac client remembers the connection in the sidebar and adds a new one. They all connect and work properly, however if you reboot/log out often you will have dozens of these. The only way that I have found is to remove each keybase device from the sidebar, one at a time.

**Comment by cjb** [comment] 2016-02-29 14:39
Thanks!  Adding @gabriel to CC.

**Comment by Deathmoon** [comment] 2016-02-29 18:20
Keybase GUI Version: 1.0.14-20160229170010+88432c3

**Comment by gabriel** [comment] 2016-02-29 21:00
Oops... yep can reproduce on El Capitan (doesn't dupe on Yosemite)... working on a fix now

**Comment by gabriel** [comment] 2016-02-29 23:13
I found the problem how we match favorites items and fixed.

Even after the fix, I still noticed it can be flakey since the favorites item is tied to a mount which can change or become invalid. When this happens the favorites item won't come back even if the mount does and there doesn't seem to be a good way programatically to figure it out.

So, I'm gonna disable it since it's so flakey.

We'll revisit the putting in favorites (probably using the finder sync extension) sometime in the future...

**Comment by gabriel** [comment] 2016-02-29 23:14
This is in master and will be in the next nightly build, update tomorrow morning

**Closed by gabriel** 2016-02-29 23:14 UTC
