### ISSUE TITLE
Can't get client to connect

### ISSUE THREAD

**Issue by acmeyer** [keybase/client#5780] opened 2017-02-09 17:14 UTC
Keybase GUI Version: 1.0.18-20170207120017+ce0f90d

Just installed, tried running the app and on the loading screen I am getting the error:

*keybase.updater is not running (updater)*

Output:
---
Installer: 1.1.46
Privileged Helper: Installed, Bundle Version: 1.0.29, Version: 1.0.29
Updater: Unknown, Install Error: keybase.updater is not running (updater)
Service: Unknown, 
Fuse: Unknown, 
Mount directory: Unknown, 
KBFS: Unknown, 
CLI: Unknown, 

Log:
Version: 1.1.46
Installables: (
    "Privileged Helper",
    Updater,
    Service,
    Fuse,
    "Mount directory",
    KBFS,
    CLI
)
Install: Privileged Helper
Connecting to keybase.Helper (privileged=1)
Connected
Helper version: {
    build = 2;
    version = "1.0.29";
}
Helper version: {
    build = 2;
    version = "1.0.29";
}
Install: Updater
Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater --timeout=30s
Task EOF
Completed
Task (err): 2017-02-09T12:12:30.158881 ▶ [DEBU keybase globals.go:352] 001 Created Identify2Cache, max age: 5m0s
2017-02-09T12:12:30.159063 ▶ [DEBU keybase globals.go:355] 002 Created LinkCache, max size: 65536, clean dur: 1m0s
2017-02-09T12:12:30.159126 ▶ [DEBU keybase globals.go:357] 003 Created CardCache, max age: 5m0s
2017-02-09T12:12:30.159155 ▶ [DEBU keybase globals.go:359] 004 made a new full self cache
2017-02-09T12:12:30.159180 ▶ [DEBU keybase globals.go:361] 005 made a new cached UPAK loader (timeout=10m0s)
2017-02-09T12:12:30.160637 ▶ [DEBU keybase ui.go:571] 006 Can't set GPG_TTY; discover failed
2017-02-09T12:12:30.160685 ▶ [DEBU keybase globals.go:335] 007 Keybase CLI 1.0.18-20170207120017+ce0f90d
2017-02-09T12:12:30.160702 ▶ [DEBU keybase globals.go:335] 008 - Built with go1.7.5
2017-02-09T12:12:30.160713 ▶ [DEBU keybase globals.go:335] 009 - Visit https://keybase.io for more details
2017-02-09T12:12:30.160731 ▶ [DEBU keybase main.go:147] 00a + configureProcesses
2017-02-09T12:12:30.160761 ▶ [DEBU keybase main.go:245] 00b + configureLogging
2017-02-09T12:12:30.160774 ▶ [DEBU keybase main.go:254] 00c Disabling log forwarding
2017-02-09T12:12:30.160785 ▶ [DEBU keybase main.go:247] 00d - configureLogging
2017-02-09T12:12:30.160801 ▶ [DEBU keybase main.go:149] 00e - configureProcesses -> <nil>
2017-02-09T12:12:30.160906 ▶ [DEBU keybase install_osx.go:405] 00f Installing components: [updater]
2017-02-09T12:12:30.160967 ▶ [DEBU keybase install_osx.go:945] 010 Using updater path: /Applications/Keybase.app/Contents/SharedSupport/bin/updater
2017-02-09T12:12:30.166116 ▶ [DEBU keybase launchd.go:141] 011 Output (launchctl remove): 
2017-02-09T12:12:30.166166 ▶ [DEBU keybase launchd.go:146] 012 Nothing to stop (keybase.updater)
2017-02-09T12:12:30.166183 ▶ [DEBU keybase install_osx.go:955] 013 Installing updater service (keybase.updater, timeout=30s)
2017-02-09T12:12:30.166298 ▶ [INFO keybase launchd.go:270] 014 Saving /Users/alex/Library/LaunchAgents/keybase.updater.plist
2017-02-09T12:12:30.166329 ▶ [DEBU keybase util.go:181] 015 + Writing to /Users/alex/Library/LaunchAgents/keybase.updater.plist
2017-02-09T12:12:30.166802 ▶ [DEBU keybase util.go:183] 016 | Temporary file generated: /Users/alex/Library/LaunchAgents/keybase.updater.plist.MKM6DLKKHJDWROE4P4SLIFZU7QTZPMXG
2017-02-09T12:12:30.166939 ▶ [DEBU keybase util.go:202] 017 - Wrote to /Users/alex/Library/LaunchAgents/keybase.updater.plist -> ok
2017-02-09T12:12:30.166988 ▶ [INFO keybase launchd.go:95] 018 Starting keybase.updater
2017-02-09T12:12:30.172365 ▶ [DEBU keybase launchd.go:98] 019 Output (launchctl load): 
2017-02-09T12:12:30.172453 ▶ [INFO keybase launchd.go:176] 01a Waiting for keybase.updater to be loaded...
2017-02-09T12:13:00.174542 ▶ [ERRO keybase standard.go:200] 01b Error installing updater service: keybase.updater is not running
2017-02-09T12:13:00.174664 ▶ [ERRO keybase standard.go:200] 01c Error installing updater: keybase.updater is not running
2017-02-09T12:13:00.178333 ▶ [DEBU keybase out_of_date.go:14] 01d + PrintOutOfDateWarnings
2017-02-09T12:13:00.178402 ▶ [DEBU keybase util.go:402] 01e + GetSocket
2017-02-09T12:13:00.178438 ▶ [DEBU keybase util.go:403] 01f - GetSocket -> ok
2017-02-09T12:13:00.178461 ▶ [DEBU keybase socket.go:73] 020 | empty socket wrapper; need a new one
2017-02-09T12:13:00.178495 ▶ [DEBU keybase socket_nix.go:96] 021 Dialing unix:/Users/alex/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
2017-02-09T12:13:00.178945 ▶ [DEBU keybase socket_nix.go:96] 022 Dialing unix:/Users/alex/Library/Caches/Keybase/keybased.sock
2017-02-09T12:13:00.179221 ▶ [DEBU keybase socket.go:88] 023 | DialSocket -> ERROR: There were multiple errors: dial unix /Users/alex/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/alex/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
2017-02-09T12:13:00.179255 ▶ [DEBU keybase out_of_date.go:19] 024 Ignoring error in printOutOfDateWarnings: There were multiple errors: dial unix /Users/alex/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/alex/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
2017-02-09T12:13:00.179287 ▶ [DEBU keybase out_of_date.go:20] 025 - PrintOutOfDateWarnings
2017-02-09T12:13:00.284582 ▶ [DEBU keybase globals.go:423] 026 Calling shutdown first time through
2017-02-09T12:13:00.284698 ▶ [DEBU keybase login_state.go:1045] 027 + Account "LoginState - Shutdown"
2017-02-09T12:13:00.284791 ▶ [DEBU keybase login_state.go:958] 028 - LoginState: Leaving request loop
2017-02-09T12:13:00.284847 ▶ [DEBU keybase login_state.go:1047] 029 - Account "LoginState - Shutdown"
2017-02-09T12:13:00.284997 ▶ [DEBU keybase globals.go:480] 02a exiting shutdown code=0; err=<nil>

Task (out): {
  "componentResults": [
    {
      "name": "updater",
      "status": {
        "code": 1804,
        "name": "ERROR",
        "desc": "keybase.updater is not running",
        "fields": null
      }
    }
  ],
  "status": {
    "code": 1804,
    "name": "ERROR",
    "desc": "keybase.updater is not running (updater)",
    "fields": null
  },
  "fatal": false
}

Install complete
Privileged Helper: Installed, Bundle Version: 1.0.29
Version: 1.0.29
Updater: Install Error: keybase.updater is not running (updater)

**Comment by cjb** [comment] 2017-02-09 17:15
Thanks for the report, CC @gabriel.

**Comment by gabriel** [comment] 2017-02-16 23:01
I think maybe your LaunchAgents folder has wrong permissions. (Some other programs have been known to create this folder with the wrong permissions.)

What is the output of:

```
ls -al ~/Library/LaunchAgents/
```

If owned by root you can fix by changing to be owned by current user:

```
sudo chown -R "$USER" ~/Library/LaunchAgents/
```

**Comment by gabriel** [comment] 2017-02-16 23:02
Closing as dupe of #5206. Thanks for reporting and please see discussion there.

**Closed by gabriel** 2017-02-16 23:02 UTC
