### ISSUE TITLE
Please Support Multiple Identities or Personas

### ISSUE THREAD

**Issue by cbluth** [keybase/client#8586] opened 2017-09-21 16:46 UTC
I have two personas online, my professional persona and my personal/family personas are kept separate online.
In this real-life example, I will *never* associate my facebook with my github via way of keybase (i wont proof facebook and github on the same keybase account, because that then associates them).

Are my concerns common, is anyone else concerned about the same thing?
Can/Will keybase support multiple personas or identities?

**Comment by cjb** [comment] 2017-09-21 17:08
We do support this. You can `keybase logout` of one account and then log in to the second.

We don't plan to make it much easier than it already is, because most people don't do this.

**Comment by junderw** [comment] 2017-09-22 00:09
I also would love the ability to be logged in to multiple accounts simultaneously.

I understand Keybase is “single identity” driven, but I think that idea is misguided.

The equivalent in GnuPG would be to say “ERROR: —genkeys: you can only generate one private key ring per instance of gnupg, please log out of current OS user and log into a new user to manage a second private keypair”

You are just creating an artificial hurdle that won’t prevent people from doing it, and will only hurt the people who try jumping over that hurdle and trip and fall and break their face.

People who want to do this will do it, so why not make it simpler for them?

If the answer is “it’s not a priority” I totally understand and can put up with the inconvenience of switching between identities.

But if the answer is “multiple email addresses are bad. multiple personas are bad, everyone should know about all your emails and PGP keys and social accounts” then I think that is misguided.

The whole “discourage multiple accounts” thing makes sense for Facebook and twitter etc. but not for keybase imo.

**Comment by bradmurray** [comment] 2017-11-03 15:41
The logout/login process is not very user friendly because if people want to run multiple identities they usually want to be able to be logged into all of them at the same time which would mean the clients should be able to handle it. Running multiple instances on win/osx/linux would work, but multiple instances on a phone are problematic.

**Comment by cbluth** [comment] 2017-11-04 16:04
@bradmurray I agree. Logging in/out is not representative of real-life, for example, any one of my acquaintances should be able to reach me at any time, despite whether they are professional acquaintances or otherwise. Just because i'm "at work" doesnt mean i shouldnt receive notifications from anyone else.

**Comment by wolfmcnally** [comment] 2018-02-14 06:32
Excellent software but honestly I'm surprised this wasn't a must-have in version 1. Part of managing one's privacy these days is managing one's identities. I know *many* people who would balk at using Keybase because they can't easily manage multiple identities.

**Comment by maxtaco** [comment] 2018-02-14 11:32
We already support this.

**Comment by dabura667** [comment] 2018-02-14 13:47
@maxtaco I just checked the iPhone app and logging in to multiple accounts simultaneously (the subject of this issue) is not yet supported.

I need to log out and log back in with a different account. During which time I can no longer get notifications for the previous account.

**Comment by bradmurray** [comment] 2018-02-14 14:34
> We already support this.

How is this already supported? I run keybase on Android, Windows and OSX and on all of them I have to logout and log back in to change identities.

**Comment by neunenak** [comment] 2018-04-14 05:32
I'm a new keybase user using it for multiple identities and I too would like to see the UX around being logged into multiple identities simultaneously become better.

**Comment by dabura667** [comment] 2018-04-14 09:28
This is a sorely missing feature, imo.

**Comment by jcausey-astate** [comment] 2018-06-22 13:33
I'll add my vote for this one as well, and also point out that the Firefox container solution doesn't help with chat -- chat seems to be only supported with the native app, with the exception of the limited chat enabled by the browser extension.  So, the browser can't really fix this issue.

I have a similar use case to others here; I have a need to keep my work-related communication separate from personal accounts.  I'm happy to see the new "exploding messages" feature; I hope this one might get some consideration now that that one is done.  (Maybe also chat search via the GUI, but that's a different issue.)

**Comment by TheKangaroo** [comment] 2018-06-29 11:55
Hey, I just started to use keybase and the first thing I checked was if I can create separate accounts for private and business use cases. It would be great to have these two logged in in the app simultaneously.

**Comment by supakeen** [comment] 2018-07-17 10:51
Jumping on this bandwagon as well. A lot of services nowadays do support multiple identities and/or personas logged in at the same time. It'd be awesome if keybase could do the same for those of us who keep separate online identities for separate areas of work.

**Comment by domq** [comment] 2018-07-24 12:04
N+1'd. An important use case is the ability to make "bot" accounts to be members in a team (e.g. to auto-push DevOps secrets into a Keybase Git repo)

**Comment by QuentinBellus** [comment] 2018-08-14 13:38
+1 on this. Multiple identities should be supported. 

> We don't plan to make it much easier than it already is, because most people don't do this.

Many people who already have accounts in different places do have one for work and one for their personal identity. I know many, MANY people in this case, and looking at the list of people in this thread, there are indeed many of us.

Please bring this to Keybase

**Comment by jfinstrom** [comment] 2018-10-01 17:54
+1 I also have personal (where I am generally opinionated on things that matter to me) and my company account (fun but filtered)

**Comment by AngryAnt** [comment] 2018-10-16 08:02
Conflicted if the "already supported" responses ought to be treated as depressing or hilarious.

**Comment by srd424** [comment] 2018-10-23 17:17
Dropping in to +1 here. Keybase looks fascinating but I have had my fingers burnt in the past by letting different areas of my life overlap (new rule: colleagues only get added on social media when one or other of us leaves!) Not doing that again!

**Comment by shrmn** [comment] 2019-01-26 07:33
Definitely want this.

**Comment by grilldos** [comment] 2019-03-15 04:08
Want this as well.

**Comment by rsoltanzadeh** [comment] 2019-03-17 21:18
> The logout/login process is not very user friendly because if people want to run multiple identities they usually want to be able to be logged into all of them at the same time which would mean the clients should be able to handle it. Running multiple instances on win/osx/linux would work, but multiple instances on a phone are problematic.

If it is not feasible on phone, then don't try to implement this for phone. Do it for the desktop app. It is (obviously) a largely overlooked feature.

**Comment by hexagile** [comment] 2019-03-20 10:51
+1000 

For me, this is a dealbreaker - as much as I love keybase, until multiple personas will be properly supported, it will be just a toy app I'm checking out every now and then.

**Comment by tstrijdhorst** [comment] 2019-04-04 12:02
+1 This is the main reason I'm not using keybase tbh.

**Comment by fortran77** [comment] 2019-04-12 04:15
It's quite understandable that software developers want to discourage or prevent account creation spam. It can clog up the namespace, for one thing. It allows Sybil attacks in dicsussions, for another, so a person can pretend to be multiple people all arguing the same side (happens on Reddit and Twitter all the time). Making it too easy for a person to have many logins will also make it too easy for the person to take up many times the free allocation of cloud storage per person.

So I definitely will not argue for multiple identities without limit.

However, two is a bare minimum, because many of us find it desirable to keep our personal and professional lives separate. If carrying a single mobile device, you would want to have both identities logged in. Or you might have separate business and personal devices, and in that case, you can much more easily implement security procedures, so certain business-related files are never allowed to touch a personal device.

You might need a third identity to say and do naughty things, not naughty enough to make you a criminal in the civilized world, but naughty enough to damage your personal or professional life if found out and, in some less civilized parts of the world, be stoned to death.

You can probably imagine reasons for additional identities.

I think about five or six would be a reasonable limit.

**Comment by IpsmLorem** [comment] 2019-04-29 17:39
Definitely a must have !

**Comment by mahmad-nutrien** [comment] 2019-06-26 15:18
I just joined a workplace that uses Keybase and would love to have the ability to simultaneously sign into my work and personal accounts.

I'd understand if it wasn't a priority though.

**Comment by maxtaco** [comment] 2019-06-26 15:26
We're close on this, either in this release or the next.

**Comment by Mikaela** [comment] 2019-07-02 10:17
In https://github.com/keybase/client/issues/2104#issuecomment-493079134 it's said that you can currently `keybase login -s anotheraccount` to switch account

**Comment by Avamander** [comment] 2019-07-23 11:49
Is there any UI support planned for this?

**Comment by junderw** [comment] 2019-07-23 12:39
yes.

however I currently can't get desktop notifications for any of the other logged in accounts. I have to switch and visually check for unread chats.

**Comment by dlumma** [comment] 2019-08-01 18:15
Please add support for this!

**Comment by ItsExtra** [comment] 2019-09-03 04:51
> I honestly can't believe someone, never mind someone responsible for a product like keybase, would honestly think "most people don't have multiple identities on the internet"

There's a subculture of people who seem to have melted their selves into the internet like butter on toast. People who do this will naturally interact with lots of others who have done the same to a greater or lesser extent so they come to believe it is normal. If a primary way you interact with other humans is online, then you might eventually arrive at the conclusion that the people posting prolifically online are representative of all humans. Because how else would you ever comes across anyone? It's a weird self perpetuating bubble. 

That said I am not sure if the devs/bosses here think this (though I haven't read all the other related issues yet so maybe they do) or if they are merely indifferent or uninterested.  

IMHO security and privacy/anonymity are intrinsically linked in every practical way. 

Like the others, I would also consider this tool much more useful if I didn't have to sit and think which portion of my life it is most suited for, which is my train of thought at the moment.

**Comment by junderw** [comment] 2019-09-03 05:57
Feature: is in current release version.

Feature Request Issue: continues discussion as if it is not there.

Feature:

![スクリーンショット_2019-09-03_14-57-16](https://user-images.githubusercontent.com/11246316/64147417-26cfa900-ce5b-11e9-8eb6-c5eee29d1c33.png)

**Comment by ItsExtra** [comment] 2019-09-03 06:18
> Feature: is in current release version.

I am new to this whole github thing but why is the issue still marked as "open"? Also #2104 "Feature Request: Logging into multiple keybase accounts locally". In my limited experience, mostly lurking, devs/admins are extremely happy to _close_ these things once they are resolved. 
 
Found this thread (and the many others which link here) trying to determine if it is possible or no. All I see is many people stating it's not possible. I can't see anything obvious on my phone about how to do this. "Add identities" lets me verify on about 800 mastodon servers.

**Comment by junderw** [comment] 2019-09-03 06:23
Because these threads get long, and after a while it's no longer clear what feature they were talking about to begin with.

Also, Keybase client has 2.6k issues open... which tells you that this project is not focused much on closing / managing issues and is more focused on coding / reviewing code.

The closed issues mostly tend to be bugs that were fixed, since they are much easier to put a binary value on completion.

**Comment by getraf** [comment] 2019-09-03 21:52
![Keybase GUI screenshot showing single persona support on 2019/09/03](http://on.getr.af/3e8afac05c31/Image%202019-09-03%20at%2016.42.09.png)

I think this issue is still open and people are still talking about this because currently, there is no Graphical User Interface (GUI) support for multiple identities or personas through the Keybase app.

Here's my +1 for GUI support in addition to the Command Line Interface (CLI) implementation.

**Comment by Avamander** [comment] 2019-09-04 11:55
@junderw 
> Feature: is in current release version.

The feature definitely doesn't exist in current version in an acceptable manner.

**Comment by w3bb** [comment] 2019-10-17 03:02
+1. Especially with chat there's times where I'd want to use alternative identities. If Keybase is aiming for businesses to support Keybase, then it would be incredibly useful to have different accounts for work and private use.

**Comment by Hexstream** [comment] 2019-10-25 20:57
Note that these days twitter allows to simultaneously connect to up to 5 accounts/identities at the same time, right there through the normal official GUI. Just click on "More" then the blue "⊕" to add more accounts. (I never use that feature, but I'm glad it exists.)

![Multiple twitter accounts](https://www.hexstreamsoft.com/tmp/twitter-multiple-accounts.png)

**Comment by Hexstream** [comment] 2019-11-06 12:19
Also note that these days, gmail (or only G Suite?) supports multiple accounts natively:
![Multiple gmail accounts](https://www.hexstream.net/tmp/gmail-multiple-accounts.png)

**Comment by w3bb** [comment] 2019-11-06 12:20
Kebase *technically* supports it, but having to re-enter your password
every time is a massive pain.

**Comment by Hexstream** [comment] 2019-11-06 14:06
Being able to be logged in to multiple accounts *simultaneously* is distinctly different.

**Comment by getraf** [comment] 2019-11-16 03:47
> ![Keybase GUI screenshot showing single persona support on 2019/09/03](https://camo.githubusercontent.com/759c383f25429b2ab28ba4e8ad15c7932e57a664/687474703a2f2f6f6e2e676574722e61662f3365386166616330356333312f496d616765253230323031392d30392d3033253230617425323031362e34322e30392e706e67)
> 
> I think this issue is still open and people are still talking about this because currently, there is no Graphical User Interface (GUI) support for multiple identities or personas through the Keybase app.
> 
> Here's my +1 for GUI support in addition to the Command Line Interface (CLI) implementation.

![Image 1 of 2 Keybase GUI screenshot showing multiple persona support on 2019/11/15](http://on.getr.af/58b46ed240a5/Image%202019-11-15%20at%209.42.22%20PM.png)

We just got our wish.

Multiple identities or personas support through the Keybase app Graphical User Interface (GUI).

That's in addition to the Command Line Interface (CLI) implementation.

Yes!

![Image 2 of 2 Keybase GUI screenshot showing multiple persona support on 2019/11/15](http://on.getr.af/686e61502e18/Image%202019-11-15%20at%209.45.49%20PM.png)

**Comment by Hexstream** [comment] 2019-11-19 18:17
Sounds great, but as soon as I select "Log in as another user" it immediately logs me out and I have to enter my password again to log back in...

**Comment by heronhaye** [comment] 2019-11-25 15:31
This is now in the app in version 5.0 on all platforms. You should be able to switch users without entering your password every time.

@Hexstream, if you have "Always stay logged in" checked in the Advanced Settings tab, that sounds like a bug. Please send feedback after reproducing and make another issue. Thanks.

**Closed by heronhaye** 2019-11-25 15:31 UTC

**Comment by Hexstream** [comment] 2019-11-25 21:08
You are right, checking "Always stay logged in" solves the problem, but this behavior is not intuitive at all. [I created a new issue](https://github.com/keybase/client/issues/21245).

**Comment by mvdan** [comment] 2020-04-19 13:10
Thanks so much for fixing this issue! I use this feature on a daily basis, and it works great.

I have two suggestions to make it even more awesome:

https://github.com/keybase/client/issues/23850 to show notifications for all accounts configured as "always stay logged in".

https://github.com/keybase/client/issues/23851 to allow switching between "always stay logged in" accounts with just a keyboard shortcut, or a single click, and remember what tab was last open for each account.
