### ISSUE TITLE
KeyBase is consuming 8% of the cpu on Sierra

### ISSUE THREAD

**Issue by dburman** [keybase/client#4706] opened 2016-10-25 18:05 UTC
macOS 10.12.1
Keybase 1.0.17 installed via brew

Process:  Kernel
Message: AMFI: allowing exception handler for 'keybase' (819) because the process is unsigned.

**Comment by maxtaco** [comment] 2016-10-25 19:00
Dupe of #4671

**Closed by maxtaco** 2016-10-25 19:01 UTC
