### ISSUE TITLE
Keybase Helper deamon keeps crashing when accessing my private folder.

### ISSUE THREAD

**Issue by CiraciNicolo** [keybase/client#6945] opened 2017-05-11 13:30 UTC
my log id: dc98f6c25d579f01ac44001c

**Comment by maxtaco** [comment] 2017-05-11 13:34
CC: @strib 

```
2017-04-01T21:41:33.750008+02:00 ▶ [DEBU kbfs(FBO c7c752d5) folder_branch_ops.go:961] 1e6 Identify finished successfully [tags:FID=vVNv0KPgm33siZhTII9sXQ]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x42832a2]

goroutine 887 [running]:
panic(0x4bc5de0, 0xc420014060)
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
github.com/keybase/kbfs/libkbfs.(*RootMetadata).Revision(0x0, 0x4e2a088)
	/Users/test/go/src/github.com/keybase/kbfs/libkbfs/root_metadata.go:634 +0x22
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).SetInitialHeadFromServer.func2.1(0xc4202e2c00, 0xc45c695e50, 0x6b34028, 0xc45c731200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/test/go/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:1528 +0xa3
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).SetInitialHeadFromServer.func2(0x0, 0x0)
	/Users/test/go/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:1529 +0x993
github.com/keybase/kbfs/libkbfs.runUnlessCanceled.func1(0xc45c7e9da0, 0xc45c73ce70)
	/Users/test/go/src/github.com/keybase/kbfs/libkbfs/util.go:25 +0x27
created by github.com/keybase/kbfs/libkbfs.runUnlessCanceled
	/Users/test/go/src/github.com/keybase/kbfs/libkbfs/util.go:26 +0x7c
2017-04-01T21:41:34.006637+02:00 ▶ [INFO kbfs start.go:31] 001 KBFS version 1.0.2-20170317000127+32601ed
```

**Comment by strib** [comment] 2017-05-11 17:15
@CiraciNicolo: Sorry for the bad experience!  Looks like your private folder has been busted for a while.  When you first wrote to it, you were on an older version of KBFS that had a known bug (#6339); it's been fixed since then, including in the current release you're running.  This is a local bug, and won't affect any other devices or folders you have.


You can work around this with the steps below. NOTE: this will erase any data you've written into the shared folder so far, so if it's important, don't run these steps and let me know and I'll try to come up with a way to recover the data from your local device (it will probably involve a special Keybase release):

# Completely shutdown all Keybase processes.
# run this command: rm -rf "/Users/$USER/Library/Application Support/Keybase/kbfs_journal/v1/0120e423329b55bb7a5c2e7dfc38953c12b3-c7c752d5909f0f1f"
# Restart Keybase

Please try this out if you're comfortable losing the _local_ data written to the folder so far, and close this out if things seem ok.  Thanks!

**Comment by CiraciNicolo** [comment] 2017-05-16 18:59
No problem! It'll be great to recover my files, can you assist me? Or can I get a list of my files so I can check if I've made a backup of those files?

**Comment by jzila** [comment] 2017-05-19 22:34
@strib: it looks like local data in the journal is the _only_ data for that TLF, given that it hasn't even been initialized.

**Comment by strib** [comment] 2017-05-19 23:44
@jzila: yep thanks (see #6339, cited above).

Sorry @CiraciNicolo, I missed that you replied here.  I made a special release that I hope will help.  Can you try to install this please?  https://s3.amazonaws.com/prerelease.keybase.io/darwin/Keybase-1.0.23-20170519233305%2Beb723ac.dmg

I hope after you install this, Keybase will stop crashing, and you'll be able to access your private directory long enough to copy all of the data out.  After that, you can follow the steps above to clear out the data on disk, and then when Keybase is restarted you can copy the data back in.

(I was unable to test this myself, so it's possible it won't help.  Please let me know how it goes, and if it doesn't work I'll try something else.)

**Comment by CiraciNicolo** [comment] 2017-06-01 15:21
Sorry for the delay! I've been busy in the real world! By the way, it keeps crashing when opening the private folder.

**Comment by strib** [comment] 2017-06-01 16:55
@CiraciNicolo: it still crashes even after you installed the dmg I linked to?  Bummer.  Can you please do another `keybase log send` with this new installation?  Thanks!

**Comment by CiraciNicolo** [comment] 2017-06-02 12:21
New log id: 11ea31aeba1213b893fea71c 

Thank you for the help.

**Comment by jzila** [comment] 2017-06-03 01:13
@CiraciNicolo when you say "redirected", what does that mean? `cd /keybase/private/you` goes to `/`?

**Comment by strib** [comment] 2017-06-03 01:14
@jzila: it is still crashing, so it's probably just going to /keybase with no mountpoint.  I need to make a new dmg, have a reminder to do so on Monday.

**Comment by CiraciNicolo** [comment] 2017-06-03 15:02
```
cd /keybase/private/ciracinicolo
<E> fish: getcwd() failed with errno 2/No such file or directory
<E> fish: getcwd() failed with errno 6/Device not configured
<E> fish: Could not determine current working directory. Is your locale set correctly?
cd: Could not set PWD variable
<E> fish: getcwd() failed with errno 6/Device not configured
 errno 6/Device not configured
```

This is the output as today.

**Comment by strib** [comment] 2017-06-03 15:25
Thanks @CiraciNicolo, I will make a new dmg for you to try on Monday.  I missed a case when I built the previous one.

**Comment by strib** [comment] 2017-06-03 21:05
Hi @CiraciNicolo, here's another special build you can try when you have time, please: https://s3.amazonaws.com/prerelease.keybase.io/darwin/Keybase-1.0.24-20170603203032%2Bbc45d6e.dmg

**Comment by CiraciNicolo** [comment] 2017-06-05 16:25
Hi @strib, it's still crashing. I'm starting thinking I'm the problem here. I had installed the latest version but running `keybase status` shows me that the KBFS version is not the same as the Keybase app.

```
Username:      ciracinicolo
Logged in:     yes
...
KBFS:
    status:    running
    version:   1.0.2-20170603203115+e1420ba
    log:       /Users/esoteric/Library/Logs/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.24-20170603203032+bc45d6e
    log:       /Users/esoteric/Library/Logs/keybase.service.log
```

**Comment by strib** [comment] 2017-06-05 17:16
Hi @CiraciNicolo, the version mismatch is normal.  We use the git hash from the KBFS repo for the KBFS version, and the hash from the client repo for the Service version.

I'm basically just guessing on how to fix your issue because I can't reproduce it, so I probably missed something.  If you do another `keybase log send` I can check why it's crashing this time, and make another incremental fix.  Sorry about all the back and forth!

**Comment by CiraciNicolo** [comment] 2017-06-11 16:22
Thanks for your help! New log id is 6c2bcd23736ee9e82531fe1c.

**Comment by strib** [comment] 2017-07-07 02:23
Hi @CiraciNicolo -- I'm really sorry for the delay!  I'm embarrassed to say this issue fell off my radar and I missed your update when you posted it.

I see now that you indeed weren't running the most up-to-date build I had made, not sure why.  I've made a new build for you based on current master.  Can you please try it out when you have a chance, if you're still interested in a fix for this issue?

https://s3.amazonaws.com/prerelease.keybase.io/darwin/Keybase-1.0.25-20170707013439%2Bcd258a316.dmg

Thanks, and sorry again for the extreme slowness on my part.

**Comment by CiraciNicolo** [comment] 2017-07-10 13:32
Hi @strib -- No problem, I've also been busy. BTW the latest build still can't fix the problem; there is a way to decrypt the fs blocks without installing the software! Or we can call it done e screw my files.

**Comment by strib** [comment] 2017-07-10 15:41
There's no way to decrypt without the software, sorry.  if it still doesn't work, please do another `keybase log send` so I can see why.

Really sorry for all the nonsense here.

**Comment by CiraciNicolo** [comment] 2017-07-13 19:14
Hi! It seems that now it is working, I can finally access my private folder! I don't know what has changed but it's working, so no problem! Thank you for your help!

**Comment by strib** [comment] 2017-07-13 19:41
Yay!

**Closed by strib** 2017-07-13 19:41 UTC
Labels: acked
