### ISSUE TITLE
Cannot create a Keybase public chat

### ISSUE THREAD

**Issue by zmanian** [keybase/client#5746] opened 2017-02-08 21:51 UTC
Keybase GUI Version: 1.0.18-20170208165022+dc66461

```
keybase chat send --public zmanian "Hello public keybase"
Creating a new PUBLIC CHAT conversation: zmanian.
▶ ERROR creating conversation error: error creating conversation: unknown TLF ID: cfc5b8a3b92e938cd3c612fa7bea2f17
```

**Comment by maxtaco** [comment] 2017-02-08 21:52
Thanks @zmanian, we're tracking down this bug, it happens to some but not others.  Can you `keybase log send`?  Many thanks!

**Comment by mmaxim** [comment] 2017-02-08 22:11
Hey @zmanian, we actually don't need the log send, we seem to have found the root cause here and are working on a fix.

**Comment by charlie-wasp** [comment] 2017-12-14 06:39
I've got version 1.0.37, got the same error

**Comment by maxtaco** [comment] 2017-12-14 14:53
thanks, cc: @mmaxim, that original bug should be fixed, i wonder if there is a new one.

**Comment by mmaxim** [comment] 2017-12-14 17:04
I think this is fallout from the server problems this morning @maxtaco, going to close. @charlie-wasp feel free to re-open if you try again and it doesn't work.

**Closed by mmaxim** 2017-12-14 17:04 UTC

**Comment by charlie-wasp** [comment] 2017-12-15 03:53
Thank you for your replies, it seems working now 👍 Keep up the good work and thank you for the Keybase!
