### ISSUE TITLE
Can't open personal private folder

### ISSUE THREAD

**Issue by llorephie** [keybase/client#6136] opened 2017-03-05 15:08 UTC
My log id: b315755d1108627ad316c61c

**Comment by strib** [comment] 2017-03-05 15:50
Hi @llorephie, it looks like you revoked all devices that have access to this folder, and then added your newest device.  So unfortunately there is no way to recover whatever data you had in that folder.  Would you mind giving us some background about how that happened, so we can improve the product?  Why did you revoke your paper key?

We can reset it for you.  If you want us to do that, please run this command on an currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/llorephie because all the devices that have access have been revoked."
```

and post the results here.

**Comment by llorephie** [comment] 2017-03-05 19:39
Thanks, @strib.
I've lost my backup and re-installed all my devices, forgot to backup Keybase keys, only main GPG survived :)

Here is signed message:

`BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbs0cfyzn CdiiUPXEHv0Ct0K 4SX71CJHyVvPFnv 3ImnPk0VpjxZ1jn zzz8FY9nZn0w584 UTR5k1mp8W28Vjq RVaMkICAk5yxDPj YhYtxqx6hDaIyQC uxCPdClBbgLLEuJ fsNlsRmraEtETFp Qjwv13QVVHGGZ7j 07xpriV94aCrbEv I7KOhwBYxtWHUfV j2Q3gO2VbByGCPC MOpuQKDVGkyShnj CHkYvgAVbq49opC RftRbFrGDFTXonI dq9y47jvkYwAa6B N1wHBDyX7YKEZsg gOzQeKGi6ahq0NF L2o193Xn0VhE4nd Xnsmxi9scmClEWR 7rmg9oS8kAwPAkO iC7asQnekNmbfsj 9ZrmrSMb6PK6XZL 0LIjSsVF70HXxXp QaV9JerxF76IkCY tc5IRbgL7Z0481s wrXAOrVmyuwmu. END KEYBASE SALTPACK SIGNED MESSAGE.`

**Comment by strib** [comment] 2017-03-05 19:59
Thanks, I'll get to this tomorrow when I'm back in the office.

**Comment by strib** [comment] 2017-03-06 18:12
Your private folder is now reset.  If things look ok to you, please close this out.  Thanks!

**Closed** 2017-03-06 19:02 UTC

**Comment by matjaz** [comment] 2017-05-30 20:00
@strib 
`keybase sign -m "2017-05-30 10pm: Please reset folder /keybase/private/matjaz because all the devices that have access have been revoked."`

```BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrzIlyzJ 7bAtjueSlhghiU7 4LJp56JF1l0S3lb wvZynQF1nMOdHpt HOA6zZD5co9deHN lKqNLoVTa8byMvg qnwe2Q0CP0VmCqO S345NpgkuseHdoG 2QbTRu6Igrjfe3B VPHUk8ujnXDlnz3 PG6GqWj1cZtbGRK 44a2V6N5m3jJmRh lyyyH5Vw1tyHGaT JtIgP7h2JNJqOxP XZvz5n5WohXMrT8 nhUF4pr0d8PKZaC h7FN6n0FQBLjOjO 61p89fyBrbBDwxg LMSSggj3Fttvveh sN6lySPCpt4tEcJ tacwDpQOHXXLaET yyEOLKJceFGtwCB 2j0Dh6bpxMEika0 VlNyPgP4lDOmk7I FC89P4jlTJgZRRb zRmxa0RixVGWQoO FhzdOFMK5XJ7nnK 7TPAfiQy3p0tzA5 H4Ay. END KEYBASE SALTPACK SIGNED MESSAGE.```

Thank you!

**Comment by strib** [comment] 2017-05-30 20:05
@matjaz: done.

Next time (for anyone else reading this in the future): please open a new ticket rather than comment on an old one.  I'm more likely to notice it that way.

**Comment by joaosilva2095** [comment] 2017-10-07 18:45
Hi!

I am joaosilva2095 in Keybase and I can't access my private folder "joaosilva2095" because I have revoked in all devices and then added a new one. Is it possible for you to reset my private folder?

Thank you!

**Comment by strib** [comment] 2017-10-07 20:19
@joaosilva2095: 
If you want us to reset your folder, please run this command on an currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/joaosilva2095 because all the devices that have access have been revoked."
```

and post the results here.

**Comment by joaosilva2095** [comment] 2017-10-07 21:07
Result:

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkXBWqkR Exasse8OueC2asj WAgZslZ1Nen5B9N YReft6shmNIqNwv AHwoGOJSS1T692c VOr8ZxlpEfZJuzu 9yozRrmZjqUBqUJ XBIJEQsn5VhGJaZ BCyTQgvpGtSrH7m 7sXFNmLy7fol5X9 4lEysSUYUDI2pGa awPnru1Cs0r6kih UXosW3j9vvNLUKo O1EGHRMY7R6Xr7X ONhZ7bZdQ8GhL5Z HSbg80GkE90ogX5 spBBF6vU9QHTYRM 05chV4kznCCZSVz dFduvSemcY3xmHv 2O3iEYFVeYZNCpP AeWiWWqv4aW3wRF cYwxm4oAKGxxYL2 bC6VfomdKgXde. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment] 2017-10-07 22:04
@joaosilva2095: I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by joaosilva2095** [comment] 2017-10-07 22:15
Ya it is working! Thank you :D (the issue is already closed I think)
