### ISSUE TITLE
Facebook: Unable to verify public post

### ISSUE THREAD

**Issue by magicdude4eva** [keybase/client#7818] opened 2017-07-19 13:22 UTC
Link to FB: https://www.facebook.com/naschenweng/posts/10213513120365439?pnref=story

**Comment by aligature** [comment] 2017-07-19 16:33
Same thing happening to me. Error 500 after posting.

**Comment by jjv** [comment] 2017-07-19 20:00
Same here, error 500 when posting. Post still displays ok in FB, even in incognito.

**Comment by maxtaco** [comment] 2017-07-19 20:01
cc: @oconnor663

**Comment by oconnor663** [comment] 2017-07-19 20:46
Confirmed, it looks like Facebook changed the behavior of the [Feed Dialog](https://developers.facebook.com/docs/sharing/reference/feed-dialog) such that our proof text no longer makes it into the final markup. Still looking into the details.

Before today:

![image](https://user-images.githubusercontent.com/860932/28388765-c200cd96-6ca1-11e7-8791-e6200db55a8d.png)

Today:

![image](https://user-images.githubusercontent.com/860932/28388784-d122e692-6ca1-11e7-95e9-b5ac4e63daf3.png)

**Comment by oconnor663** [comment] 2017-07-20 02:39
Here's an example dialog URL that tries to set all the supported parameters: https://www.facebook.com/dialog/feed?app_id=1614372842200926&link=jacko.io&name=bar&caption=baz&description=bing&thumbnail=blarg.jpg

If we load that, it looks like none of the parameters have any effect anymore:

![image](https://user-images.githubusercontent.com/860932/28398011-178ede2a-6cd3-11e7-9914-49d2d205b5f8.png)

**Comment by oconnor663** [comment] 2017-07-20 21:03
@magicdude4eva @aligature @jjv: This bug should be fixed now. Can you confirm by making new Facebook proofs?

**Comment by Regner** [comment] 2017-07-20 22:02
Worked for me just now and was not working earlier.

**Comment by jjv** [comment] 2017-07-20 22:04
@oconnor663: Working just fine now! 👍

**Comment by oconnor663** [comment] 2017-07-20 22:10
Woo!

**Closed by oconnor663** 2017-07-20 22:10 UTC

**Comment by aligature** [comment] 2017-07-20 22:25
Worked for me!

**Comment by magicdude4eva** [comment] 2017-07-21 07:01
Thank you very much for the quick fix!
