### ISSUE TITLE
Keybase stopped working after installation of Mojave Beta

### ISSUE THREAD

**Issue by docdyhr** [keybase/client#13620] opened 2018-09-06 20:17 UTC
Keybase stopped working after installation of Mojave Beta

my log id: dfd9611b9f70181986613c1c

**Comment by strib** [comment] 2018-09-06 20:18
@docdyhr what do you mean by "keybase"?  Do you mean the whole app, or just the file system integration with Finder?

**Comment by docdyhr** [comment] 2018-09-06 20:26
I have tried to remove Keybase and reinstall it again. But the problems reappear.. this time around I tried to remove the config files as well. What to do?

**Comment by strib** [comment] 2018-09-06 20:26
Ok, then this is probably a duplicate of #13537, and of your own issue #13552.  We're actively working on a potential fix.  Let's keep the discussion on #13537 please.

**Closed by strib** 2018-09-06 20:26 UTC
Labels: acked

**Comment by docdyhr** [comment] 2018-09-06 20:29
ok.
