### ISSUE TITLE
OSX notifications on wake from sleep

### ISSUE THREAD

**Issue by offbyone** [keybase/client#2222] opened 2016-03-04 17:59 UTC
Sadly, I don't have the text from them, because they came and went and didn't stick around the notification center. But aroun 07:24 today was the first one in the log below.

my log id: f212bd4c74093be8cb547d1c

**Comment by jzila** [comment] 2016-03-04 18:08
It looks like you would have received a disconnect notification around 07:24:38, and a reconnect notification around 07:24:58. @offbyone did you see anything other than those two notifications?

**Comment by cjb** [comment] 2016-03-04 18:10
(You can go to the OSX "Notification center" to see which notifications you received.)

**Comment by offbyone** [comment] 2016-03-04 18:19
They don't show up in the notification center, sadly. I may have them filtered somehow (something I clearly need to tweak)

**Comment by jzila** [comment] 2016-03-04 18:20
Do you remember if it was anything other than connect/disconnect? If so, what was the gist of them and what made them alarming?

**Comment by offbyone** [comment] 2016-03-04 18:22
I don't, I'm sorry. I was talking to a friend as I connected, and saw it out of the corner of my eye and just processed enough to realize it was an error of some kind.

**Comment by jzila** [comment] 2016-03-04 18:24
Ok. In this instance a disconnect notification followed by a connect notification is expected. Your log indicates to me that this is all that happened. Would you be okay with closing the issue, and you can reopen it if you get more detail that is different from expected behavior?

**Comment by offbyone** [comment] 2016-03-04 18:25
Absolutely.

**Closed** 2016-03-04 18:25 UTC
