### ISSUE TITLE
Failed to load file metadata/An unexplainable error has occured

### ISSUE THREAD

**Issue by Espionage724** [keybase/client#21330] opened 2019-12-02 07:35 UTC
![Screenshot from 2019-12-02 02-33-14](https://user-images.githubusercontent.com/6378956/69938759-1b1c6e80-14ac-11ea-9adf-cf7c1431f649.png)

I've had this happen for a few days now, and it happens on both Windows and Linux.

How to reproduce:

1. Click Files
2. Click private
3. Click my username
4. Get the following errors: Failed to load file metadata: espionage724, An unexplainable error has occured, Failed to list folder: espionage724

**Comment by strib** [comment] 2019-12-02 14:46
If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by Espionage724** [comment] 2019-12-02 14:54
Done: 90def6375e8f4849daec131c

**Comment by strib** [comment] 2019-12-02 19:52
Thanks for the info, and sorry for the bad experience.  I looked into it and it seems the problem is that the folder was last written by a device that you revoked on 11/24.  That is normally fine, it just causes the KBFS client to do some extra work to verify that the device was valid at the time the write happened.  Unfortunately, it looks like when you revoked the device, your local clock was off by about 8 hours.  This is causing confusion in the code that checks the device validity, and is causing your client to not trust the folder contents at all because it looks sketchy.

Unfortunately this security measure is hardcoded into the client and there's no easy way to disable it. If you want, I can make a custom linux build for you that would disable that -- then you can write to the folder with a valid device and that should fix the problem going forward, assuming you also fix your clock skew issue.  Let me know if you want to do that.

We will also be looking into the problem where we allowed too much clock skew in the first place, but that future fix won't help your current problem.

**Comment by Espionage724** [comment] 2019-12-02 20:00
Yeah, if you wouldn't mind, I'd like to try the custom Linux build.

I believe I ran into this problem when using Windows, and either not updating my clock after install, or booting into Linux and running into the Local/UTC time difference thing.

**Comment by strib** [comment] 2019-12-02 22:45
@Espionage724 ok I made this build for you: https://s3.amazonaws.com/tests.keybase.io/linux_binaries/deb/keybase_5.0.0-20191202223046.5ad11b6d4f_amd64.deb

It is the same as 5.0.0 but with one extra commit: https://github.com/keybase/client/commit/5ad11b6d4f89b05e7782154643b1e28b32867c71

If you install it, you should be able to read your folder again, and you should write something new to it as well, from a valid device.  After that, it should be fixed everywhere, and you can either downgrade back to the normal 5.0.0 release, or wait for our next release which should get installed over this one like normal.

Let me know how it goes.

**Comment by Espionage724** [comment] 2019-12-03 18:35
Thanks! I installed it in a VM, logged in, accessed the folder, created a file, and it seems to load up fine on my main OS. Everything looks fine now

**Closed** 2019-12-03 18:39 UTC
Labels: acked
