### ISSUE TITLE
Firefox extension can't reach installed Keybase client on Fedora

### ISSUE THREAD

**Issue by xavrb** [keybase/client#8754] opened 2017-10-02 15:05 UTC
To my knowledge, Firefox extension must connect automatically with the installed client, but in this case it doesn't -- it always shows a blue button that asks for me to install the kb client. This is from the Firefox menu and the button on social media. 
Tried restarting the browser and system (Fedora).

Keybase client version throws: 
`Client:  1.0.31-20170917003451+ed4bf6a71`

Firefox extension is `1.10.6`

**Comment by PhML** [comment] 2017-11-20 22:34
Same troubles here:
keybase version 1.0.33
Archlinux
Mozilla Firefox 57.0
Chromium 62.0.3202.94 
Keybase Extension 1.10.6

Duplicate of #8061 ?

**Comment by jaredsmith** [comment] 2018-01-07 02:07
I'm seeing the same thing, and as a former Fedora Project Leader, I'd love to help get this solved.

**Comment by maxtaco** [comment] 2018-01-07 02:11
Thanks for the report!

cc: @oconnor663

**Comment by oconnor663** [comment] 2018-01-08 19:54
@PhML it looks like your version of Keybase is super out of date. Could you repeat the install instructions here: https://keybase.io/docs/the_app/install_linux. I run Gnome Shell on Arch, and I find that the Firefox extension works when `aur/keybase-bin` is installed.

**Comment by oconnor663** [comment] 2018-01-08 22:02
@jaredsmith I have a repro on a Rawhide VM on my end. Will keep playing with it to see what's up.

**Comment by oconnor663** [comment] 2018-01-08 22:26
Ok, it looks like the problem is that we install /usr/lib/mozilla/native-messaging-hosts/io.keybase.kbnm.json, but Firefox 57 on Fedora Rawhide only looks in /usr/**lib64**/mozilla/native-messaging-hosts. If you link the latter to the former and restart Firefox, it seems to make the extension start working.

I notice that on Arch, `/usr/lib64` is just a symlink to `/usr/lib`. So whatever the underlying rule is for where Firefox is going to look, that's probably why I never saw an issue.

**Comment by oconnor663** [comment] 2018-01-08 22:45
[This page](https://wiki.mozilla.org/WebExtensions/Native_Messaging) suggests that `/usr/share/mozilla/native-messaging-hosts` might also work, but it didn't seem to work for me. It would be easy to add both `lib` and `lib64` to the package, but I'm worried about a weird interaction if we try to package two filepaths that might end up referring to the same path on some systems. @jaredsmith do you have any suggestions?

**Comment by jaredsmith** [comment] 2018-01-08 23:30
I was hoping that `/usr/share/mozilla/native-messaging-hosts` would work since that's the proper location for shared extensions that don't depend on any arch-specific code.

On Fedora, the next best location would be `/usr/lib64/mozilla/native-messaging-hosts/<name>.json` on a 64-bit host, and `/usr/lib/mozilla/native-messaging-hosts/<name>.json` on a 32-bit host.

**Closed** 2018-01-10 19:20 UTC

**Comment by oconnor663** [comment] 2018-01-10 19:33
@jaredsmith could you please help me test this after our next build goes out? Probably tomorrow around noon.

**Comment by jaredsmith** [comment] 2018-01-10 19:35
Absolutely 😁

**Comment by jaredsmith** [comment] 2018-01-15 14:44
Seems to be working great.  Thanks @oconnor663
