### ISSUE TITLE
Instability in Windows 10 16257

### ISSUE THREAD

**Issue by dkackman** [keybase/client#8022] opened 2017-08-04 22:56 UTC
I'm running Windows 10 insider preview 16257.rs3_release.170728-1700. Installed windows client. The keybase login hung and after a subsequent reboot, windows itself would lock up about 30 seconds after logging into the OS. 
Reverting to a restore point in windows got things back to normal but I'm afraid I no longer have the version of keybase that was installed. It was the version linked on the homepage on 8/3/2017.

**Comment by loudambiance** [comment] 2017-08-05 03:51
I can confirm that this issue is also present in Windows Build: 16251.rs3_release.170721-2122. It took me 3 and half hours to figure out it was keybase causing the issue (I did not have a restore point to revert to).

**Comment by jzila** [comment] 2017-08-07 05:01
Dupe of #7591

**Closed by jzila** 2017-08-07 05:01 UTC
