### ISSUE TITLE
tried to save small file on semi crappy coffee shop internet

### ISSUE THREAD

**Issue by adammenges** [keybase/client#4390] opened 2016-09-22 20:00 UTC
blue bottle in palo alto, not great wifi but not insanely bad either, file is <1mb

my log id: cbabd3057f89bf27cfd5121c

**Comment by strib** [comment] 2016-09-23 17:53
Thanks for the report!  The file write error was caused by a known bug, which is fixed in the newest release.  (Unrelated to the usual large write errors.)  Unfortunately it looks like you're on Sierra, so the next release will disable KBFS for you while we're looking for a workaround to the Sierra hang issue.  Lame -- hopefully this is a very temporary situation.

I also see another failure in the log for a timeout on a SetAttr call.  During this time it looks like we (the KBFS servers) were getting throttled by our storage provider so things were a little slow.  Sorry about that!

**Comment by adammenges** [comment] 2016-09-23 19:29
Thanks for the hard work guys. The world's a better place with keybase in it.

**Comment by strib** [comment] 2017-03-15 17:43
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.

**Closed by strib** 2017-03-15 17:43 UTC
