### ISSUE TITLE
High CPU usage while others are typing

### ISSUE THREAD

**Issue by yohanboniface** [keybase/client#16329] opened 2019-03-01 16:25 UTC
Hi,

I'm running KeyBase on ArchLinux:

```
$ keybase --version
keybase version 3.0.0
```

As soon as another user is typing, I see an electron process with a very high CPU usage:

![screenshot from 2019-03-01 17-10-06](https://user-images.githubusercontent.com/146023/53651183-58ff1480-3c46-11e9-840a-355b5161bb0a.png)

I see I can opt out from typing notification from the settings, but in an ideal world it's useful to know when other are typing not to speak all in the same time :)

Anything I can do to workaround this? To help narrowing down the issue?

Thanks!

**Comment by heronhaye** [comment] 2019-03-01 16:34
Thanks for the report. This should be fixed in our next release. 

In the meantime, if you like, you could try the current master build by installing `keybase-git` from the AUR (conflicts with other packages) and letting us know if the problem is fixed for you. You can reinstall the original package after if you don't want to be on nightly.

**Comment by yohanboniface** [comment] 2019-03-02 08:03
Thanks for your answer :)

The `keybase-git` package seems to be 3.0.0 too:

```
aur/keybase-git 3.0.0-1 (11, 0,000727)
    the Keybase Go client, filesystem, and GUI
```

Or did you mean `keybase-bin` ?

```
aur/keybase-bin 3.0.0_20190205202117+6394d03e6c-1 (120, 1,2896)
    the Keybase Go client, filesystem, and GUI
```

Thanks :)

**Comment by heronhaye** [comment] 2019-03-02 14:49
`keybase-git` is a source package, so it will download the latest source from GitHub and compile it on your machine whenever you install it. So it will always be the latest version of Keybase (usually still in testing).

**Comment by yohanboniface** [comment] 2019-03-02 15:01
> keybase-git is a source package, so it will download the latest source from GitHub

It could be pointing to a specific branch or tag ;)

But OK, thanks for the tip :)

**Comment by heronhaye** [comment] 2019-03-15 19:00
Closing this out since we did a stable release with the fix. Please make another issue if you still run into high CPU usage, thanks!

**Closed by heronhaye** 2019-03-15 19:00 UTC
Labels: electron, linux
