### ISSUE TITLE
Something went wrong...

### ISSUE THREAD

**Issue by pmarsceill** [keybase/client#9434] opened 2017-11-08 18:16 UTC
![screenshot 2017-11-08 13 15 32](https://user-images.githubusercontent.com/896475/32566753-ed21d398-c486-11e7-9645-0bdc48320b75.png)

my log id: 949cdd22a8ed52228909391c

Not really sure what else to report except that the "People" tab is completely unusable for me now. I tried quitting the app and it doesn't have any effect.

**Comment by denmch** [comment] 2017-11-12 18:16
I had the same issue today (log id `4b0549820b003c46b7184f1c`) on MacOS Sierra.

There was nothing unusual in the log (at `/Library/Logs/keybase.system.log`). As noted, the error was limited to the people tab, but for me more specifically to 'search' on the people tab.

The issue recurred for me for several minutes, temporarily fixed by restarting the app, but since touching the log to have a look, I haven't been able to reproduce the error.

**Comment by pmarsceill** [comment] 2017-11-13 21:31
I rebooted my machine a few times, and it eventually went away but I have no idea what the resolution was or what caused it.

**Closed** 2017-12-05 20:57 UTC
