### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by golddranks** [keybase/client#2296] opened 2016-03-11 16:28 UTC
I'm trying to write simple `echo "hello" > test.txt`
in `/keybase/private/golddranks,japsu`.
It says: `-bash: test.txt: Input/output error`
Drag&dropping files there in Finder doesn't work either. (Error -36)

`japsu` is a keybase user that exists but I'm not sure if he uses the filesystem.

Writing to another folder, `/keybase/private/akx,golddranks`, works.

my log id: a950df8cb5dc8f70311ccb1c

**Comment by golddranks** [comment] 2016-03-11 16:41
It says in the docs that "you can't yet share with non-Keybase people (e.g., /keybase/private/golddranks,pal-not-on-keybase@twitter)." Maybe this is it? Gonna ask my pals if they're using the Filesystem.

**Comment by cjb** [comment] 2016-03-11 16:52
Do you see any "tracker popup" for Japsu in the Keybase app, prompting you to retrack him?

There is a problem with one of his proofs:

✖ Proof for japsu.fi failed: 404 Not Found (code=240)

But you should be being prompted to retrack him, to fix the problem.

**Comment by golddranks** [comment] 2016-03-11 17:29
I'm not seeing such a popup. Neither when trying to access the folder from terminal, nor from Finder.

Btw. my Keybase app just updated itself (and I reopened all the folders), but that seemed to fix nothing.

**Comment by cjb** [comment] 2016-03-11 18:08
Thanks.  It sounds like the bug here is that we didn't display the popup.  I wonder if it's because there are two proofs for japsu.fi, one web and one DNS, and one of them works.  We'll investigate.

**Comment by golddranks** [comment] 2016-03-11 18:17
Great! Thanks.

**Comment by cjb** [comment] 2016-03-11 18:28
Oh, and to unblock yourself, feel free to run `keybase track japsu` to fix your track by removing the broken proof.

**Comment by chrisnojima** [comment] 2016-03-22 14:55
I've tried to reproduce this with the latest updates and the tracker is appearing correctly given these circumstances. Let's close this and reopen if it happens again. Thanks!

**Closed by chrisnojima** 2016-03-22 14:55 UTC
