### ISSUE TITLE
Keybase Using lots of CPU

### ISSUE THREAD

**Issue by koehn** [keybase/client#3918] opened 2016-08-16 22:02 UTC
Keybase GUI Version: 1.0.16-20160803190018+268b023
macOS 10.12 Beta (16A284a)

App routinely uses about 75% CPU as reported in Activity Monitor.

**Comment by cjb** [comment] 2016-08-16 22:13
Hi, we don't support Sierra yet, I'd bet the CPU usage is being caused by something being broken there.

**Comment by mikz** [comment] 2016-09-12 06:42
The same here. Given it is RC1 now it might be good time to start taking a look.

**Comment by notahat** [comment] 2016-09-21 03:31
Seeing the same thing on the actual release of 10.12.

**Comment by Sharpie** [comment] 2016-10-11 20:26
If `poll()` is being used, a possible candidate is: https://daniel.haxx.se/blog/2016/10/11/poll-on-mac-10-12-is-broken/

**Comment by triangletodd** [comment] 2016-10-18 15:45
Yep. This is where it hangs in the logs:

> 110450 2016-10-18T11:43:38.610429 ▶ [DEBU keybase main.go:456] 029 + Enter ListenLoop()

**Comment by bleys** [comment] 2017-04-08 22:42
`poll()` bug is confirmed fixed in macOS 10.12.2.  Close?

Promisingly, Keybase avg energy impact (0.61 as I look now) is just above Finder and just below iStat Menus Status. However, a Keybase Helper process is my #1 CPU time user, clocking over an hour in a day. This is without me using Keybase at all in that time. Seems like it's still overactive in the background, even without poll bugs.

**Comment by maxtaco** [comment] 2017-04-10 01:46
Thanks for the report. CC: @keybase/react-hackers

**Comment by gabriel** [comment] 2017-04-10 19:33
Yeah animated gifs are still resource intensive...
https://keybase.atlassian.net/browse/DESIGN-1022

**Comment by gabriel** [comment] 2017-04-10 20:49
We did a workaround here:
https://github.com/keybase/client/pull/6495

Will be available in next public build.

**Closed by gabriel** 2017-04-10 20:49 UTC

**Comment by maxtaco** [comment] 2018-11-20 13:54
@dnickerson do a `keybase log send` if you want us to look into it. It's almost certainly a different issue from the above BTW

**Comment by joar** [comment] 2019-03-04 12:19
@maxtaco chiming in, my log id is 5b1fd4f9cbc9c996dd07f81c

**Comment by maxtaco** [comment] 2019-03-04 12:30
@joar this an electron bug, @heronhaye knows more about it.

**Comment by heronhaye** [comment] 2019-03-04 14:52
@joar on linux? Should be fixed in the next release, but if you like you can try out a nightly at https://keybase.io/docs/linux-user-guide#nightly-builds and let us know if it is better.
