### ISSUE TITLE
Can't Add Device

### ISSUE THREAD

**Issue by JeremyRubin** [keybase/client#10032] opened 2017-12-23 05:03 UTC
I'm trying to add a new desktop device, but it fails silently in the gui after entering the text code.

In the shell, it gives ERROR EOF. 

my log id: d79c4ad7be8fe9acb862cc1c

**Comment by maxtaco** [comment] 2017-12-23 13:47
Sorry for the bug. Can you send feedback from the other device?

**Comment by maxtaco** [comment] 2017-12-23 13:49
I.e., run `keybase log send` from `Workstation`?

**Comment by JeremyRubin** [comment] 2017-12-24 04:34
log id: 0044b89d698f9c2cc288081c

I was able to get it working by using my paper key.

**Comment by maxtaco** [comment] 2017-12-24 18:22
Thanks @JeremyRubin. We'll look into it when we're back at the office after the holiday..

**Comment by maxtaco** [comment] 2017-12-27 15:26
@JeremyRubin, from the logs, it looks like:

* On the new machine, you chose to provision with `Nothanks`
* It took a little bit of time to get to `Nothanks`
* And that you didn't use QR codes, you just entered text (as reported above)

I think what happened is that `Nothanks` gave up after 5 minutes, and retired those text codes, but the errors didn't propagate properly on `Workstation` to let you know that, so there was no way to know. We'll look into fixing this.. Thanks!

**Comment by pauby** [comment] 2018-06-05 11:39
Any progress on this?

**Comment by maxtaco** [comment] 2018-06-05 12:31
Try it again. What happens?

**Comment by pauby** [comment] 2018-06-05 12:40
I think the point of the issue is if it's left for more than 5 minutes the new device isn't added and no warning is given. In my case it simply goes back to the 'Add Device' screen which leaves me wondering what on earth is going on. 

If I refresh the phrase on the new device (by clicking Back and logging in again) and then immediately going to the device I need to add it on, it works.

**Comment by maxtaco** [comment] 2018-06-05 12:47
As I recall, we bumped the timeout way up, to about an hour, as a result of
this ticket.

**Comment by maxtaco** [comment] 2018-06-05 12:48
See here: https://github.com/keybase/client/blame/master/go/engine/kex2_provisioner.go#L110

**Comment by pauby** [comment] 2018-06-05 12:59
Okay - thanks. Why is this ticket still open? And if it's an hour then my issue must be something else because I typed it in, max, 10 minutes after getting it.

**Comment by maxtaco** [comment] 2018-06-05 13:00
Closing, thanks for your help

**Comment by maxtaco** [comment] 2018-06-05 13:00
@pauby open a new ticket then.  logs from both devices is usually most helpful

**Closed by maxtaco** 2018-06-05 13:00 UTC
Labels: acked
