### ISSUE TITLE
Enable Keybase in Finder is not working fine

### ISSUE THREAD

**Issue by rodrigolopestalkdesk** [keybase/client#24727] opened 2021-12-10 11:34 UTC
Keybase GUI Version: 5.8.0-20210920184218+ac2177aec7

**Comment by foss-** [comment] 2021-12-15 11:57
Sounds like a dupe of https://github.com/keybase/client/issues/24636
If you agree, please close this bug.

**Closed** 2021-12-15 12:17 UTC
