### ISSUE TITLE
[Feature Request] Universal iOS support for the iPad

### ISSUE THREAD

**Issue by garrettoreilly** [keybase/client#9082] opened 2017-10-16 21:50 UTC

**Comment by specious** [comment] 2017-12-17 16:21
It would be incredibly useful not to have to rotate the iPad into portrait orientation every time just to use Keybase.

![28d6fc07-1e67-4fbb-8c1d-7ca65e6f4a31](https://user-images.githubusercontent.com/451178/34081558-497508b4-e31c-11e7-9ada-ecbaa440e915.png)

**Comment by specious** [comment] 2017-12-17 16:31
Looks like universal support was enabled in #6230 and removed in #6836.

**Comment by BergQuester** [comment] 2019-05-29 20:36
Dupe of #8909 which as of writing has an open pull request.

**Closed** 2019-05-29 20:40 UTC
