### ISSUE TITLE
Team Folders with Word

### ISSUE THREAD

**Issue by OliverGrabowski** [keybase/client#9688] opened 2017-11-27 14:05 UTC
When I open a Word document straight from a team folder in Windows Explorer make changes and save I get an error message saying that I don't have access permission.  If I save the file somewhere else and then move (or copy/paste) it into the team folder it works fine.  It asks me if I would like to replace the old file and allows me to do so.  I can open the file in Word again.  But still can't save directly into the folder from Word.
Using Windows 10 (non admin account), Word 2016 and as a writer in the team.  I've tried as 2 different writers, on 2 different computers, with different Windows logins.  64 bit Windows, Word and PC.

**Comment by strib** [comment] 2017-11-27 14:12
@OliverGrabowski: that is very weird.  Can you please run a `keybase log send` from the shell and report the resulting log ID here, so we can investigate?  Thanks!

(Also, I'm curious if you've tried Word in your regular, non-team private folder, and if that works.)

**Comment by strib** [comment] 2017-11-27 15:39
Logs: 01fd5ae655549cd5e1715d1c

**Comment by strib** [comment] 2017-11-27 18:35
@taruti: can you please take a look?  I can't find any obvious error messages related to Word but I'm not great at debugging the dokan stuff.

**Comment by OliverGrabowski** [comment] 2017-11-27 18:49
I've since tried as the team owner, with an admin Windows login. Same team. I get the same error. Access permission error. It's a Word error popup. It's a fully registered version of Word and Windows. Definitely just a problem with the Key base file system. I tried in a private non team folder. Same problem.

**Comment by taruti** [comment] 2017-11-29 16:42
This is caused by a new Windows feature in Windows 10 build 16299 (and up).

It has been now fixed in upstream Dokan https://github.com/dokan-dev/dokany/issues/611

Thus we need to upgrade the Dokan driver.

**Closed** 2017-11-29 17:04 UTC
Labels: acked
