### ISSUE TITLE
Keybase App shows only blank panes

### ISSUE THREAD

**Issue by tml** [keybase/client#4472] opened 2016-09-30 16:52 UTC
I recently uninstalled the version of keybase I had initially installed, and attempted to install a newer version. This has resulted in Keybase showing me only blank panes.

Host is OS X El Capitan on a MacBook Pro (Retina, 15-inch, Mid 2015).

Here's a screenshot of the menu bar item showing a blank pane:

![image](https://cloud.githubusercontent.com/assets/35148/18999891/0c8da388-86fd-11e6-9599-3a07f56e5702.png)

And Keybase.app:

![image](https://cloud.githubusercontent.com/assets/35148/18999638/e873929c-86fb-11e6-8343-a36652eebafa.png)

**Comment by cjb** [comment] 2016-09-30 16:59
Sorry about this.  Please could you run `keybase log send`?

After that, I think that if you kill Keybase processes and restart from the Applications folder, it'll work.

CC @gabriel

**Comment by tml** [comment] 2016-09-30 17:03
my log id: 0d8a0a66097a6eab5cc90f1c

I have tried killing the Keybase processes, rebooting the machine, and even uninstalling and reinstalling the Keybase client (both the previous working one and the one that first exhibited the problem.) Nothing seems to recover these panes.

**Comment by cjb** [comment] 2016-09-30 17:12
Thanks, we'll get on this.

(I see from your log that our Electron BrowserWindows are crashing, and also that an install step hung.)

**Comment by chrisnojima** [comment] 2016-10-03 15:20
@gabriel note we have a stack trace in the gui log for the installer. Please take a look at that

**Comment by cjb** [comment] 2016-10-03 15:27
@chrisnojima (it looks like the stack trace is caused by the installer itself sending SIGABRT to `keybase install` after it times out.)

**Comment by gabriel** [comment] 2016-10-03 18:41
@tml Can you post another log send, am curious to see more logs from when you rebooted etc? And if same error message is coming up...

Some notes from reading logs:

- **Service starts**: 2016-09-29T17:37:42.188951 ▶ [DEBU keybase globals.go:265] 007 Keybase CLI 1.0.17-20160922174631+f87e42c
- **Start app**: Thu Sep 29 2016 17:37:56 GMT-0600 (MDT) (1475192276018): Version: 1.0.17-20160922174631+f87e42c
- **Installer runs**: Thu Sep 29 2016 17:37:56 GMT-0600 (MDT) (1475192276095): Executing: /Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod
- **Installer finishes**: Thu Sep 29 2016 17:38:19 GMT-0600 (MDT) (1475192299468): Exec (stderr): 09.29.2016 17:37:56.229 Installer... **Output truncated though?**
- **App window unresponsive**:  Thu Sep 29 2016 17:38:52 GMT-0600 (MDT) (1475192332900): Browser window unresponsive: { preventDefault: [Function: preventDefault],
- **KBFS restarts**: 2016-09-29T17:40:28.762799 ▶ [INFO kbfs start.go:27] 001 KBFS version 1.0.2-20160922174706+fe68a67

`Browser window unresponsive` issue seems like it would be the cause of white screen. (It's unclear from logs what causes that though.)

Around this time " Thu Sep 29 2016 17:38:52 GMT-0600 (MDT) ", KBFS seems ok, Keybase did a rekey before this but seemed fine.

There are some other things which are a little weird but might not be the source of the problem:
- The installer finished but the output was truncated
- The installer ran for 23 seconds which is long
- Why did KBFS restart 2 mins after installer exited?

In more logs if we see the window unresponsive error coming up again (everytime a white screen shows) it might indicate something is blocking synchronously the renderer thread?

**Comment by mrscobbler** [comment] 2016-10-04 22:49
I just installed the Keybase client app (I've never installed it before) and had the same issue. Ran the log command and here's my log id: dadf1230c78f3a0b2e5c631c

**Comment by gabriel** [comment] 2016-10-06 00:53
@cjb I see some browser window crashes in the log

@mrscobbler If you kill Keybase and re-run does it fix it:

```sh
pkill Keybase
open /Applications/Keybase.app
```

**Comment by gabriel** [comment] 2016-10-07 20:29
@chrisnojima found the issue and we have a fix and are testing

**Comment by chrisnojima** [comment] 2016-10-11 15:34
This is the relevant pr: https://github.com/keybase/client/pull/4560

Thanks!

**Comment by chrisnojima** [comment] 2016-10-17 14:45
The PR has been merged and should be in the next update. Let's reopen if this happens again. Thanks!

**Closed by chrisnojima** 2016-10-17 14:45 UTC
