### ISSUE TITLE
White screen on Linux when clicking the Git button

### ISSUE THREAD

**Issue by MakotoTheKnight** [keybase/client#8864] opened 2017-10-06 05:54 UTC
I'm attempting to use the encrypted Git feature and am seeing a white screen come up in the client instead.

my log id: 27548d96c958cf57ac380f1c

**Comment by dakira** [comment] 2017-10-06 12:11
Keybase GUI Version: 1.0.34-20171006000413+5fe91ae13

**Comment by maxtaco** [comment] 2017-10-06 12:12
We will investigate first thing.  Can you do a ‘keybase log send’ ?

**Comment by dakira** [comment] 2017-10-06 12:14
Log ID: 52e5f51f980733162205cd1c

**Comment by maxtaco** [comment] 2017-10-06 12:22
Thanks. Cc @oconnor663

**Comment by maxtaco** [comment] 2017-10-09 16:26
Dupe of #8872 and now fixed in master

**Closed by maxtaco** 2017-10-09 16:26 UTC

**Comment by oconnor663** [comment] 2017-10-09 16:30
(fix should be out already if you upgrade to latest)

**Comment by dakira** [comment] 2017-10-09 16:37
Confirming fix.

**Comment by MakotoTheKnight** [comment] 2017-10-09 16:45
I am confirming the fix as well.
