### ISSUE TITLE
windows app creates conflict with existing mapped drive

### ISSUE THREAD

**Issue by JonBoley** [keybase/client#3237] opened 2016-06-28 14:13 UTC
_From @JonBoley on June 28, 2016 14:3_

I already had a drive mapped to `K:\`, so when Keybase created a drive, it overwrote the existing mapping but the description still indicates the old position.
In the screenshot here, it was something called `\\usglvcpg01\cpg`:
![kbfs_bug](https://cloud.githubusercontent.com/assets/5214393/16418268/a7b80f76-3d0e-11e6-9457-96553c46c2ff.png)

Perhaps it should allow the user to specify the drive letter? 
Or at least warn that the previous mapping will be overwritten.

_Copied from original issue: keybase/keybase-issues#2319_

**Comment by cjb** [comment] 2016-06-28 14:15
Hi, I'll close this as a duplicate of #3195.  I think we'll have a fix soon.

**Closed by cjb** 2016-06-28 14:15 UTC

**Comment by zanderz** [comment] 2016-11-15 15:54
You can now choose the mount point by issuing `keybase kbfsmount set X:` and rebooting.
