### ISSUE TITLE
keybase.kbfs not running

### ISSUE THREAD

**Issue by daneov** [keybase/client#5805] opened 2017-02-10 14:59 UTC
Whenever Keybaserestarts (manually _or_ in the event of a reboot), I receive the error : 
<img width="450" alt="screen shot 2017-02-10 at 09 34 26" src="https://cloud.githubusercontent.com/assets/7900887/22831214/d4a187d0-efa9-11e6-970d-99f67afa2ffa.png">

I used kbfs before, shared files with others and received some, so I'm not sure why this started.

OS: MacOS 10.12.2 Beta  (issue exists from before joining the MacOS beta program)
my log id: 979477a1927f81f2e30e451c

**Comment by daneov** [comment] 2017-02-10 15:04
`kextstat | grep kbfuse` gives me no output
The command `/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --install-fuse --timeout=60 --run-mode=prod --app-path=/Applications/Keybase.app` list elsewhere didn't fix anything.

It reports the following: ```2017-02-10T16:02:11.502139 ▶ [DEBU keybase socket_nix.go:96] 015 Dialing unix:/Users/daneo/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
2017-02-10T16:02:11.502272 ▶ [DEBU keybase socket.go:88] 016 | DialSocket -> ok
2017-02-10T16:02:11.503009 ▶ [DEBU keybase out_of_date.go:28] 017 Got OutOfDateInfo: keybase1.OutOfDateInfo{UpgradeTo:"", UpgradeURI:"", CustomMessage:"", CriticalClockSkew:0}
2017-02-10T16:02:11.503039 ▶ [DEBU keybase out_of_date.go:44] 018 - PrintOutOfDateWarnings
2017-02-10T16:02:11.606878 ▶ [DEBU keybase globals.go:424] 019 Calling shutdown first time through
2017-02-10T16:02:11.606976 ▶ [DEBU keybase login_state.go:1045] 01a + Account "LoginState - Shutdown"
2017-02-10T16:02:11.607080 ▶ [DEBU keybase login_state.go:958] 01b - LoginState: Leaving request loop
2017-02-10T16:02:11.607123 ▶ [DEBU keybase login_state.go:1047] 01c - Account "LoginState - Shutdown"
2017-02-10T16:02:11.607263 ▶ [DEBU keybase globals.go:481] 01d exiting shutdown code=0; err=<nil>

02.10.2017 16:02:11.614 KBTask:73[DEBG] Task (out): {
  "version": "3.5.2",
  "bundleVersion": "3.5.2",
  "kextID": "com.github.kbfuse.filesystems.kbfuse",
  "path": "/Library/Filesystems/kbfuse.fs",
  "kextStarted": false,
  "installStatus": 4,
  "installAction": 1,
  "mountInfos": [],
  "status": {
    "code": 0,
    "name": "OK",
    "desc": "OK",
    "fields": null
  }
}

02.10.2017 16:02:11.636 KBInstaller:45[INFO] Install complete
02.10.2017 16:02:11.636 KBInstaller:49[INFO] Fuse: Installed, Version: 3.5.2
Kext ID: com.github.kbfuse.filesystems.kbfuse
Kext Loaded: No
Path: /Library/Filesystems/kbfuse.fs
02.10.2017 16:02:11.637 Installer:82[INFO] Exit(0)```

**Comment by gabriel** [comment] 2017-02-10 18:48
If I remember correctly, I don't think KBFS works on the macos beta (there was a fuse compatibility issue)

**Comment by gabriel** [comment] 2017-02-10 22:20
Oh wait, are you on a beta of 10.12 or the beta of 10.12.2?

**Comment by gabriel** [comment] 2017-02-10 22:21
Are you running any anti-virus or vpn software (seeing if it might conflict with fuse)?

Does the issue resolve after rebooting?

Are you able to load osxfuse?

```
brew cask install osxfuse
/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse; echo $?
```

**Comment by gabriel** [comment] 2017-02-10 22:25
I just was able to reproduce if VMWare is running on my machine.

Are you running VMWare. What if you close it, does Keybase work then?

**Comment by gabriel** [comment] 2017-02-10 23:03
This is dupe of https://github.com/keybase/client/issues/5507
Please see discussion there. Thanks for reporting.

**Closed by gabriel** 2017-02-10 23:03 UTC
