### ISSUE TITLE
KeybaseUpdater keeps uninstalling Keybase on macOS

### ISSUE THREAD

**Issue by jomo** [keybase/client#5835] opened 2017-02-12 14:54 UTC
# Update: see [below](https://github.com/keybase/client/issues/5835#issuecomment-279252114)

I have no idea what's going on. I'm on the latest version of macOS Sierra, using Keybase.app `Version 1.0.18-20170208165022+dc66461 (1.0.18-20170208165022+dc66461)`.

I hadn't used the client for a while and noticed the `keybase` binary was no longer in my path. I just downloaded the latest desktop client and installed it, the binary came back, everything working fine.

The next day Keybase.app and the keybase binary are gone. I re-installed it and one day later I run into the same issue. I've reproduced this a number of times now, in one case it must have been uninstalled *while running* because it couldn't find any of the images used in the app.

I'm logged in as a non-admin user but admin credentials are provided during installation.

I couldn't find anything relevant about Keybase in `/var/log/*` and so far, Keybase is the only app that keeps disappearing. Is there anything that triggers a Keybase uninstall?

**Comment by jomo** [comment] 2017-02-12 21:39
It just happened again while it has been open the whole time, here's a screenshot where the app fails to find its own images:
![image](https://cloud.githubusercontent.com/assets/3585743/22866174/e3881402-f171-11e6-8359-7962e25086c7.png)

I didn't even reboot my machine nor put it to sleep since last installing it (although this doesn't cause the issue, as I previously tested).

**Comment by jomo** [comment] 2017-02-12 21:46
I think I know what's happening now. Looking at `~/Library/Logs/keybase.updater.log`:

```
2017/02/12 16:47:36 INFO [Applying update]
2017/02/12 16:47:36 INFO Unzipping "/var/folders/zl/<foo>/T/KeybaseUpdater.<bar>/Keybase-1.0.18-20170209165653+17b641d.zip" to "/var/folders/zl/<foo>/T/KeybaseUpdater.<bar>/Keybase-1.0.18-20170209165653+17b641d.zip.unzipped"
2017/02/12 16:47:41 INFO Moving existing destination "/Applications/Keybase.app" to "/var/folders/zl/<foo>/T/KeybaseUpdater.<bar>/Keybase.app"
2017/02/12 16:47:41 INFO The error was a problem renaming (moving) the app, let's trying uninstalling the app via keybase uninstall which has more privileges
2017/02/12 16:47:41 DEBG Execute: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase [uninstall --components=app]
2017/02/12 16:47:42 DEBG Executed /Applications/Keybase.app/Contents/SharedSupport/bin/keybase [uninstall --components=app]
2017/02/12 16:47:42 INFO We uninstalled the app, let's try to apply again
2017/02/12 16:47:42 INFO Unzipping "/var/folders/zl/<foo>/T/KeybaseUpdater.<bar>/Keybase-1.0.18-20170209165653+17b641d.zip" to "/var/folders/zl/<foo>/T/KeybaseUpdater.<bar>/Keybase-1.0.18-20170209165653+17b641d.zip.unzipped"
2017/02/12 16:47:46 INFO Moving /var/folders/zl/<foo>/T/KeybaseUpdater.<bar>/Keybase-1.0.18-20170209165653+17b641d.zip.unzipped/Keybase.app to /Applications/Keybase.app
2017/02/12 16:47:46 DEBG Remove temporary directory: "/var/folders/zl/<foo>/T/KeybaseUpdater.<bar>"
2017/02/12 16:47:46 INFO Reporting: https://api.keybase.io/_/api/1.0/pkg/error.json map[version:[1.0.18-20170208165022+dc66461] upd_version:[0.2.8] error_type:[apply] description:[Update Error (apply): rename /var/folders/zl/<foo>/T/KeybaseUpdater.<bar>/Keybase-1.0.18-20170209165653+17b641d.zip.unzipped/Keybase.app /Applications/Keybase.app: permission denied] install_id:[29b872480dc0735897a2451ccd033a50b2dd2fde7fd1e41d] request_id:[6e6336ac18f3d577f0cbbf1f]]
2017/02/12 16:47:47 INFO Exiting for restart
```

> Update Error (apply): rename /var/folders/zl/9vjdqjb93vqfcry21cyk34y00000gn/T/KeybaseUpdater.FUBNXCYMNPOEBK6SHKRVCEQ4COKZYWCHGLWGNZOTEOEKIIC5N6GQ/Keybase-1.0.18-20170209165653+17b641d.zip.unzipped/Keybase.app /Applications/Keybase.app: permission denied

The problem seems to be that administrator permissions are required to install applications (i.e. write to /Applications/) but a non-administrator account is used to apply the update. The same issue occurs when moving the outdated app but - as can be read in the log - is solved by running `keybase uninstall --components=app`.

**Comment by cjb** [comment] 2017-02-12 21:55
Thanks for debugging, CC @gabriel

**Comment by gabriel** [comment] 2017-02-13 00:00
Yeah I can reproduce, this happens if you aren't running as the user that installed the app.

The issue is updater is able to remove the old app, but can't place the new app in /Applications afterwards. I'll have to pinpoint why (looks like maybe this behavior changed on Sierra), but we should be able to have a fix soon.

(In the meantime, if we do an update this week, you might see it happen again.)

**Comment by gabriel** [comment] 2017-02-16 00:10
Fix is here: https://github.com/keybase/client/pull/5873

Should be in and available in the next few weeks.

**Comment by michaeldavie** [comment] 2017-02-24 23:32
I've been hit by this a couple times. Would installing it in my home folder (~/Applications) avoid the issue in the meantime?

**Comment by gabriel** [comment] 2017-03-01 23:59
Yeah that should work

**Comment by gabriel** [comment] 2017-07-11 18:59
This should be fixed.

**Closed by gabriel** 2017-07-11 18:59 UTC
