### ISSUE TITLE
kbfs does not start - network issue

### ISSUE THREAD

**Issue by heronhaye** [keybase/client#17349] opened 2019-05-03 18:11 UTC
copying from https://github.com/keybase/client/issues/15721

@atoponce: 

>I had a hard drive failure that brought down my workstation. After replacing the drive, and restoring my /home data from backup, I cannot mount KBFS.

>Log send. The log id is 7616850f8e5e0a2574efae1c.
```
$ ls -d $(keybase config get -d -b mountdir)
ls: cannot access '/run/user/1000/keybase/kbfs': No such file or directory
$ mkdir $(keybase config get -d -b mountdir)
$ ls -d $(keybase config get -d -b mountdir)
/run/user/1000/keybase/kbfs
$ run_keybase   
Unmounting and shutting down kbfsfuse...
Shutting down keybase service...
Starting via systemd...
Job for kbfs.service failed because a timeout was exceeded.
See "systemctl --user status kbfs.service" and "journalctl --user -xe" for details.
```

**Comment by heronhaye** [comment] 2019-05-03 18:13
@atoponce, I moved this to a new ticket because it is unrelated to the last one.

We checked out the logs but didn't see anything obvious. Is your internet connection reliable? Is chat working ok in the GUI?

**Comment by atoponce** [comment] 2019-05-03 18:43
I'm running this remotely through SSH right now. I have a stable low latency symmetrical gigabit connection to the Internet from this machine.

**Comment by heronhaye** [comment] 2019-05-03 19:49
Does that machine have a good connection? Seems some requests to the Keybase servers are timing out.

**Comment by atoponce** [comment] 2019-05-05 20:42
Let's go ahead and close this issue. As mentioned, I have a stable low latent symmetrical gigabit connection to the internet; I work for a local ISP. All network troubleshooting got me no where, but rebooting the machine seemed to have fixed the issue, as I needed to reboot anyway to confirm that /home/ would mount again after replacing the drive, and restoring data from backup.

However, I would like to reach out to someone about disk administration in ~/.local/share/keybase/, but that can be handled out of band.

Thanks for willing to investigate this issue with me, but it seems that a reboot fixed it, whatever "it" was.

**Comment by atoponce** [comment] 2019-05-05 20:54
Cancel that. I just deleted my previous reply. What I thought was data getting written to KBFS, was data getting written to an unmounted, empty directory. I still cannot mount KBFS. Here are the results of an `mtr(1)` to Keybase:

    $ mtr -rw keybase.com
    Start: 2019-05-05T14:51:10-0600
    HOST: xxxxxxxxxxx                                       Loss%   Snt   Last   Avg  Best  Wrst StDev
      1.|-- vl20.gw.slc.xmission.net                           0.0%    10    2.0   2.0   1.7   2.4   0.2
      2.|-- br2.core.xmission.net                              0.0%    10    0.4   0.4   0.3   0.4   0.0
      3.|-- te0-0-1-0.nr11.b020767-1.slc01.atlas.cogentco.com  0.0%    10    1.1   1.2   1.1   1.4   0.1
      4.|-- te0-0-2-1.agr11.slc01.atlas.cogentco.com           0.0%    10    1.5   1.4   1.3   1.6   0.1
      5.|-- 154.54.89.21                                       0.0%    10    1.6   1.5   1.4   1.6   0.1
      6.|-- be3038.ccr22.den01.atlas.cogentco.com              0.0%    10   11.5  11.6  11.4  11.7   0.1
      7.|-- be3036.ccr22.mci01.atlas.cogentco.com              0.0%    10   23.4  23.5  23.2  23.7   0.2
      8.|-- be2832.ccr42.ord01.atlas.cogentco.com              0.0%    10   34.9  35.1  34.8  35.4   0.2
      9.|-- be2718.ccr22.cle04.atlas.cogentco.com              0.0%    10   42.4  42.5  42.2  42.8   0.2
     10.|-- be2994.ccr32.yyz02.atlas.cogentco.com              0.0%    10   49.3  49.3  49.1  49.5   0.1
     11.|-- 38.108.65.35                                       0.0%    10  107.9  98.3  47.1 291.7  91.7
     12.|-- 172.18.18.244                                     10.0%    10   47.2  68.2  47.1 193.0  48.9
     13.|-- 68-68-0-81.applecreek.pathcom.com                  0.0%    10   47.2  47.2  47.1  47.5   0.1
     14.|-- 68-68-0-11.applecreek.pathcom.com                  0.0%    10   48.0  48.2  47.8  48.9   0.4
     15.|-- 68-68-1-218.applecreek.pathcom.com                 0.0%    10   47.6  47.6  47.5  47.8   0.1

As you might be able to tell from the paste, my box is on the XMission network, a local ISP out of Salt Lake City. It has a stable, low-latent symmetrical gigabit Internet connection, on both IPv4 and IPv6.

Open to suggestions.

**Comment by heronhaye** [comment] 2019-05-06 13:40
Do you know if this issue with KBFS coincided precisely with the hard drive issue? You might try deleting the cache, that could've gotten messed up when you restored your home directory.

1) Ensure you know your password by logging out and logging back in
2) Shut down keybase
3) Delete `~/.local/share/keybase` (this will log you out)
4) Start keybase back up again
5) If KBFS still isn't working, do another log send please

**Comment by atoponce** [comment] 2019-05-06 15:53
> Delete `~/.local/share/keybase` (this will log you out)

To clarify, you're requesting the entire `~/.local/share/keybase/` directory and all files and subdirectories be removed?

Is there documentation about how to properly administer this directory? I know that [writes to KBFS are cached here](https://keybase.io/docs/kbfs/understanding_kbfs#journaled-writes), in the event of a network error, and the data doesn't initially make it to Keybase. However, the data in this directory grows and grows getting to the point that it's a legitimate storage concern for disk space.

Earlier, I made the mistake of rsync-ing my /home/ dir to /keybase/private/ as a temp backup, and the process slowed to a crawl, while I also notice that /home/ was ever-growing.

**Comment by heronhaye** [comment] 2019-05-06 16:04
>To clarify, you're requesting the entire ~/.local/share/keybase/ directory and all files and subdirectories be removed?
Yeah, this is safe (but will delete all your caches so Keybase might be slow for a bit afterwards). And will also log you out.


>However, the data in this directory grows and grows getting to the point that it's a legitimate storage concern for disk space.
It shouldn't grow forever. Do you remember what the max size of that folder you saw was?

>Earlier, I made the mistake of rsync-ing my /home/ dir to /keybase/private/ as a temp backup, and the process slowed to a crawl, while I also notice that /home/ was ever-growing.
Probably best to exclude `~/.local` and `~/.cache`. Looks like your local mount is is not in your home directory though so it shouldn't have been recursive or anything.

**Comment by atoponce** [comment] 2019-05-06 16:47
Everything is golden. I'm logged in, and have access to my data.

> Do you remember what the max size of that folder you saw was?

Around 85 GB.

> Probably best to exclude `~/.local` and `~/.cache`.

Fair enough. I have a local LUKS drive for backing up `/home/` rather than going to Keybase; it was just a temporary stop gap at that time. But, are there any commands to clean up that data after Keybase has confirmed it has the data in tact?

**Comment by heronhaye** [comment] 2019-05-06 17:23
> Around 85 GB.
That seems like a bug. cc @strib

**Comment by strib** [comment] 2019-05-06 17:49
Yes @atoponce from your log it looks like you're stuck in a conflict state, where the data you're writing to your local device is not being uploaded to our servers.  I haven't followed this whole issue but if you've messed with that directory r had a hard drive issue in the past it could be related, or you could have triggered a Keybase bug some time in the past (we've fixed several recently, so hopefully new releases are better).

@atoponce if there's data in your `/keybase/private/atoponce` on that device that you don't have a local copy of, you should back it up somewhere on the local disk first.  Then if keybase itself is running (you don't need the mountpoint for this), you can try running this command:

```
keybase fs clear-conflicts /keybase/private/atoponce
```

If that works, you should be able to start re-uploading your saved data to your private folder again.  If that doesn't work, let me know and I can give you instructions on another way.

@heronhaye it's pretty dangerous to nuke that folder, since they could lose all un-uploaded KBFS data.

**Comment by heronhaye** [comment] 2019-05-06 17:51
>@heronhaye it's pretty dangerous to nuke that folder, since they could lose all un-uploaded KBFS data.
My bad, didn't know this.

**Comment by atoponce** [comment] 2019-05-06 20:33
@strib After nuking `~/.local/share/keybase/`, and re-logging in, KBFS is mounted, and I have access to my data. i was aware that `~/.local/share/keybase/` was keeping a cached journal of pending writes to KBFS, but it also seems to hold on to that data after KBFS has the data in full. However, I knew that I did not have any pending writes waiting to go to KBFS. As a system administrator, I still would like some documentation on how to manage the data stored in ~/.local/share/keybase/` so I can keep it under control.

Regarding `keybase fs clear-conflicts`, even though the help output states that `[path-to-folder]` is optional, it actually errors out with exit code 2 unless you provide an absolute path. With that said, I get the error "ERROR Unexpected merged head in setHeadPredecessorLocked". I'm guessing there is nothing to clear though, as KBFS is mounted, running, and in a clean state?

**Comment by strib** [comment] 2019-05-06 20:37
Cool yeah if you already nuked that directory, then there is nothing to clear, so disregard that suggestion.  It's a bug in the documentation that `[path-to-folder]` seems optional -- should be required.  I can fix that.

>  it also seems to hold on to that data after KBFS has the data in full.

No, it should clear the journaled data once it is sent to KBFS.  There is a separate cache (in the same directory) for recently-accessed blocks, but it's capped to 10% of your available disk space, or 20 GB, whichever is smaller.  In your logs there was definitely a problem with syncing data to KBFS though, and that's what was taking up all the space.  I'm glad whatever the data was didn't turn out to be important.

https://keybase.io/docs/kbfs/understanding_kbfs is the most complete documentation we have.

**Closed** 2019-05-14 19:48 UTC
