### ISSUE TITLE
Can't use keybase filesystem. Permission denied.

### ISSUE THREAD

**Issue by jbwiv** [keybase/client#9950] opened 2017-12-18 14:15 UTC
I have three devices (linux box, mac, and android) connected to my account. I can't access my /keybase/private directory from any of them. On each, I get:
`
 ERROR This device does not yet have read access to directory /keybase/private/d1rewolf, log into Keybase from one of your other devices to grant access: <redacted> is not readable by d1rewolf (uid: <redacted>)
github.com/keybase/kbfs/libkbfs.isReadableOrError
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/md_util.go:74
github.com/keybase/kbfs/libkbfs.(*KBFSOpsStandard).getMaybeCreateRootNode
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/kbfs_ops.go:600
github.com/keybase/kbfs/libkbfs.(*KBFSOpsStandard).GetOrCreateRootNode
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/kbfs_ops.go:641
github.com/keybase/kbfs/simplefs.(*SimpleFS).getRemoteRootNode
	/Users/build/go/src/github.com/keybase/kbfs/simplefs/simplefs.go:737
github.com/keybase/kbfs/simplefs.(*SimpleFS).getRemoteNode
	/Users/build/go/src/github.com/keybase/kbfs/simplefs/simplefs.go:748
github.com/keybase/kbfs/simplefs.(*SimpleFS).SimpleFSStat
	/Users/build/go/src/github.com/keybase/kbfs/simplefs/simplefs.go:564
github.com/keybase/kbfs/vendor/github.com/keybase/client/go/protocol/keybase1.SimpleFSProtocol.func26
	/Users/build/go/src/github.com/keybase/kbfs/vendor/github.com/keybase/client/go/protocol/keybase1/simple_fs.go:957
github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*callRequest).Serve
	/Users/build/go/src/github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/request.go:76
github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*receiveHandler).handleReceiveDispatch.func1
	/Users/build/go/src/github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/receiver.go:121
runtime.goexit
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:2337
`

What can I do to fix this?

**Comment by jbwiv** [comment] 2017-12-18 15:57
log id: d8444246b29c7da1df6df41c

**Comment by strib** [comment] 2017-12-18 18:16
@jbwiv: that folder is only keyed for your device "danger", which you seem to have revoked.  That means there's no way for us to recover any of the data in the folder.

If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/d1rewolf because all the devices that have access have been revoked."
```

and post the results here.

**Comment by strib** [comment] 2017-12-18 18:20
Hmm, looking at your account history, I don't know why the folder didn't get keyed for your device `phone` when you used `danger` to provision it.  It looks like there was more that a day between those events.

If you still have the device `danger`, it would be great to get logs from it if possible.

**Comment by jbwiv** [comment] 2017-12-18 18:22
"danger" is physically the same machine as "hdesk", I just revoked it and
re-added it as a different name. I doubt that helps with the logs, though :(

**Comment by jbwiv** [comment] 2017-12-18 18:30
Done. Thanks.

**Comment by strib** [comment] 2017-12-18 19:21
I see part of what went wrong.  At the time you provisioned `phone`, your folder was "staged" on your local device.  This means it was collecting local modifications, but wasn't syncing them to our servers, because it thought the server had a different view of the folder than it had locally.  The "different view" part comes, I think, from the fact that the new `phone` device requested access to the folder (which involves modifying the folder) at roughly the same time `danger` was writing data into the folder.

At this point, `danger` started writing a LOT into the folder, while it was staged.  Our code was trying to resolve the conflict with the server, but it couldn't because new data kept coming in.  Eventually, there was too much data to resolve it within a reasonable amount of time.

So the folder remained staged.  And, we don't allow the folder to be "rekeyed" for new devices while it's staged.  By the time you revoked `danger`, it still hadn't been able to fix the conflict and rekey, so at that point the folder is lost.

This is pretty terrible, I'm very sorry you hit it.  We'll work on fixes on our end to prevent this kind of thing in the future.  Do you have any data in that folder that isn't recoverable?  Do you want us to reset it?

**Comment by strib** [comment] 2017-12-18 19:43
Slight analysis amendment: the original conflict was between git commits you were making and file system writes, not with the phone requesting a rekey.  There seemed to be a bunch of git commits and file systems writes happening at the same time.  (Which is fine, that is supposed to work.)

**Comment by strib** [comment] 2017-12-18 20:50
Ok, sounds good.  Can you please follow the instruction I mention in my first comment to sign a message about resetting the folder, please?  For our internal records.

**Comment by jbwiv** [comment] 2017-12-18 20:53
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkDKzWp2 K3opl5I59UlJIsh 1uczkZbuTP9PZnX JOKg6AdteEf0xy4 5V564BJrAT7CKyN qaL9OhUF4Xv0lv2 MkQNKvQFsfAzoir U1DnjsuIJisBxq5 TYlQsLfjSPFufv1 Rn9MaMu8iWeYxpo QjRXLzCRCH2D6RH 3iXlSTfPKqSbSvH wN4vBFjJZ59JHwA O7tljO3a65TzeTr AG5FqNBeQTMFAiy 6yL11WqRbguXUYc 2X1QQ9tDWID9mhq MSqJ9axmT6iqPZg MNHv4s0Me4WxXQQ O1rONKLsnzL2UXg tpERtmRsBGIsJJt 0ebUf6mgOdcVC. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment] 2017-12-18 20:58
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by thepatrick** [comment] 2018-04-06 22:07
I have this problem as well. I have _never used_ the filesystem... why can't I reset this myself?

**Comment by strib** [comment] 2018-04-06 22:16
@thepatrick feel free to follow the instructions above if you need a reset.  The filesystem was used for a lot of different things, including chat, so you might have used it without knowing it.

**Comment by loogitak** [comment] 2018-05-25 04:33
I am having the same issue. I have not revoke the device . I installed the keybase app in my system and reset the app. And created a new device. Is resetting and creating a new device revoke the previous device automatically?

**Comment by jonodrew** [comment] 2018-06-02 13:15
Hi @strib can I please get a reset too?

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk8PrNve AoqXc34vJX6zImu p6pvuBIYL22gfoa yp5X8G6BVKAOg07 j15efezzCVLMmMi vWn0hJd8riOweAW X3BFzZW1CPJxD2c edQF65fgPch4c0q WDGVaLo6oySjJ6P V8QFWdt6TSkLlR1 zuFIx06fINAdpga 8GZRLfdC3fkdzyj lYnCze5Aq6FTZAT qxIYdNym8qH9bGJ ihi1VdaGUF9fbPF CbfzTsaFLZVEMoR dfTPEp24auFYeyt ixGcV1Fqy3iBo9n 4s1rpdrCJCzaH5e QOzQeKGi6ahq0NF L2o193Xn0VhE4nd Xnsmxi9scmClEW9 ovbAherEAI. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment] 2018-06-02 14:30
@jonodrew can you please do a `keybase log send` first and report the resulting log ID here, so I can see exactly what kind of problem you're having?

@loogitak If by "reset the app" you mean you went to the keybase.io website and reset your whole account, then yes that is kind of the same as revoking all your devices.  You can also do a `keybase log send` and put the log ID here so I can see what's happening.

**Comment by strib** [comment] 2018-06-02 14:31
Oops @jonodrew I see you already did that: 9a1ce1a6ce083c6a852bea1c

**Comment by strib** [comment] 2018-06-02 14:34
@jonodrew you don't need a reset, you're running a version of Android that has a bug.  It will get fixed with the next Android release.  Sorry for the inconvenience!

**Comment by strib** [comment] 2018-06-03 16:31
@jonodrew thanks for the new logs 754947dd05a5f43a2f8a721c and 224459b25d44debf170f2b1c.  Now that the other bug is gone, I see you do need a reset.  So I reset the folder.  Please check it out and let me know if everything seems ok.  (Might require a Keybase restart.)

**Comment by JamsheedMistri** [comment] 2018-06-04 21:06
@strib Not sure if my issue applies, but I just installed Keybase on my macOS High Sierra today and enabled Keybase in Finder. When I try to `cd /keybase` I get a permission denied. Log: `d6af3af72cf6067d01a56f1c`. What should I do?

**Comment by JamsheedMistri** [comment] 2018-06-04 21:28
@strib Restarting Keybase worked, thank you very much. Would you like me to post an issue about this, or is it already known?

**Comment by strib** [comment] 2018-06-05 00:10
@JamsheedMistri already know, thanks!  cc: @jzila.

**Comment by nstgc** [comment] 2018-08-03 17:09
Due to a power outage I'm working from the local library. I have a repo with my work which I pushed to before turning my desktop off last night.

I get to the library, log into keybase, and try to git clone the repo, but am presented this this same sort of message.

If I'm reading the above correctly, the issue before has been that multiple operations were underway at the same time. This is not the case here. I logged in to this keybase account for the first time on this device today (using a paper key).

As far as I can tell, this device has been initialized to use this keybase account. Otherwise I wouldn't be able to do anything at all. In `keybase device list` my laptop is listed.

I went out on a limp and tried `keybase device add` and was told I needed to rekey?

I recently had this account reset because I forgot the password and didn't have any paper keys. However if that is the cause of all this, why was I able to access my keybase git remote last night from my desktop?

**Comment by strib** [comment] 2018-08-03 17:11
@nstgc  If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by nstgc** [comment] 2018-08-03 17:24
Sending

**Comment by nstgc** [comment] 2018-08-03 17:26
Okay. The send failed.

**Comment by strib** [comment] 2018-08-03 17:27
Please post what the error was here, and then try again. If you're unable to communicate with our servers for some reason, it could explain your issues.

**Comment by nstgc** [comment] 2018-08-03 17:28
``
$ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
Enter feedback (or <Enter> to send): 
▶ INFO ignoring UI logs: GUI main process wasn't found
▶ ERROR API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
``

That error or another one? I'm trying again now.

**Comment by nstgc** [comment] 2018-08-03 17:30
It failed again.

As mentioned I'm using my phone as a hotspot because the Library's WiFi refused to work with my computer (its suppose to produce a splash screen, but. . .)

**Comment by strib** [comment] 2018-08-03 17:36
Unfortunately without seeing your logs I'm not sure how to help you, and your network seems too slow to upload your logs.  @patrickxb is my interpretation of that error message correct?

**Comment by nstgc** [comment] 2018-08-03 17:37
I got it to send. I had to turn my VPN off.

**Comment by strib** [comment] 2018-08-03 17:39
Log ID is 3a063f4241fabbb7ed0d641c, I think.  Looking now.

**Comment by nstgc** [comment] 2018-08-03 17:40
That's what it says on my end.

Thanks for confirming.

**Comment by strib** [comment] 2018-08-03 17:45
@nstgc that device of yours doesn't have access to the folder yet.  Since you haven't tied this github account to your keybase account yet, I don't want to expose your keybase account name or any of your device names here.  But it seems like something weird happened when you provisioned this device with your paper key, maybe you shut down too quickly after doing so.

Try `keybase rekey paper` from the command line, enter your paper key, and see if that helps.

**Comment by nstgc** [comment] 2018-08-03 17:46
That makes sense. I was at home running on battery power and was trying to preserve the batter.

**Comment by nstgc** [comment] 2018-08-03 17:47
I don't have the paper key on, but I can head home. I can't get much work done with out that repo.

**Comment by nstgc** [comment] 2018-08-03 17:50
Also, thank you for not exposing the user name. You guys take this stuff very seriously. I was extremely pleased when I lost all access to my data upon resetting this account.

**Comment by nstgc** [comment] 2018-08-03 19:23
Thanks. That fixed it.

**Comment by wackou** [comment] 2019-10-22 13:23
Seems like I'm having the same issue. Here's my log id: `0eb768d22884486f39502c1c`
and the signed message asking for reset:
```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkTfzdZg C2f1kyMVGxx1NoK s5tCEVGEbEQmGzr AKC723kkQAMi63L 8tuiaNThjA8Tr4H zred0b4Q6DxftXl 4TMrTeEQB3kdRm1 CCTdKHJZdMw2EFB RyhcVlFw926lAom sVN1RrpafsrYMPi J2W81fDJY37Z352 TNi7aCwD3C5m5do 2DDgBCWOgTwqL85 kt1oePheJ7z3VR0 xuI7sWfjXQJOIDn adTDeAYEX1XyLcH wSEN6mvleG50Dsu ZyrqXrhs0MgS880 TUBfR63QYjKVqyI 7O3WXNCEfHlndFH I1BMj47lRiDpspn 0CGyzD48Yj8AC50 aybxRb1a. END KEYBASE SALTPACK SIGNED MESSAGE.
```
Thanks for any help you can provide!

**Comment by strib** [comment] 2019-10-22 16:09
@wackou I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by wackou** [comment] 2019-10-23 08:01
@strib everything looks like it's working fine, thanks a lot!

(btw I can't close this issue as it's not mine, I just piled up on an issue that looked like it exhibited my symptoms)

**Closed** 2019-10-23 16:12 UTC
Labels: acked
