### ISSUE TITLE
Uninstaller listed as malware

### ISSUE THREAD

**Issue by dainok** [keybase/client#7896] opened 2017-07-26 07:36 UTC
Keybase GUI Version: 1.0.26-20170724101459+b095a79

The upd.exe process is reported as a malware by some antivirus:

https://www.virustotal.com/it/file/70b6675fac69b755dc716b1b6ee14617df15d340eb0aea7f91f3de120fcc603f/analysis/

**Comment by Oneiroi** [comment] 2017-07-26 13:12
Same on OSX, unconfirmed on Linux.

**Comment by kkarhan** [comment] 2017-08-02 12:47
i just tested the keybase_i386.deb client installation package - so far, it seems clean
https://virustotal.com/en/file/de8ded63c444d82a0bf914f5b07bb3b094250249a8440d7cb86581e7e828b888/analysis/1501677173/

Also your scan only contains 4/64 positives - all of them are crappy generic heuristic errors caused by the fact that the program is making a connection to the internet.


FYI: Linux does not need uninstallers, since either an application is portable [deleting the folder uninstalls it], or it's a package that can be uninstalled with just a single line of code.

Only crappy operating systems without proper update mechanisms or package management [i.e. Windows] need uninstallers - at least when the software devs aren't using MSI files and don't want users to simply uninstall stuff using control panel -> software -> remove software.

**Comment by zanderz** [comment] 2017-08-02 17:59
upd is the updater, not uninstaller.
This is a duplicate of https://github.com/keybase/client/issues/7908

**Closed** 2019-05-16 19:44 UTC
